src/include/common/object_pool.h, test/include/storage/tuple_access_strategy_test_util.h
(not that it really matters in our use case at this point, just for best software engineering practice I guess),
=> Use delete[] where appropriate 

.clang-format, CMakeLists.txt, cmake_modules/SetupCxxFlags.cmake, src/CMakeLists.txt, src/include/common/common_defs.h, src/include/common/concurrent_bitmap.h, src/include/common/concurrent_map.h, src/include/common/concurrent_queue.h, src/include/common/logger.h, src/include/common/macros.h, src/include/common/object_pool.h, src/include/common/printable.h, src/include/common/statistics.h, src/include/storage/storage_defs.h, src/include/storage/tuple_access_strategy.h, src/include/util/string_util.h
=> Modified formatting scripts to use 120 character lines

.dockerignore, .travis.yml, Dockerfile, script/installation/packages.sh, src/util/string_util.cpp, test/storage/tuple_access_strategy_test.cpp
Enables both Darwin and Ubuntu 18.04 Docker builds on Travis.
=> Enable Travis builds

.travis.yml
=> Enable make lint on Travis.

cmake_modules/ThirdpartyToolchain.cmake
=> disable jemalloc due to ASAN issue.

src/include/common/macros.h, src/include/storage/storage_defs.h, src/storage/data_table.cpp, test/include/util/multi_threaded_test_util.h, test/include/util/storage_test_util.h, test/storage/data_table_concurrent_test.cpp, test/storage/data_table_test.cpp
Using assert(condition && message).
Please double-check the messages I added.
=> Require an explanatory message in PELOTON_ASSERT.

test/include/util/storage_test_util.h, test/transaction/mvcc_test.cpp
Made the tests clearer, and added comments.
=> Refactored MVCC anomaly tests

src/include/type/type_id.h, src/include/type/type_util.h
@lmwnshn needs this for the plan nodes, and I need this for schema.
=> TypeId enum class from Peloton

benchmark/storage/data_table_benchmark.cpp, benchmark/storage/tuple_access_strategy_benchmark.cpp, src/include/storage/storage_defs.h, src/main/terrier.cpp, test/include/util/storage_test_util.h
The num_attrs argument was redundant.
=> Refactor BlockLayout constructor to take single argument

benchmark/storage/data_table_benchmark.cpp
Add DataTable benchmarks for 
- sequential reads
- random reads
- concurrent random reads
=> Add DataTable read benchmark

test/storage/large_garbage_collector_test.cpp, test/transaction/large_transaction_test.cpp
Add test cases for low abort high throughput scenarios
=> #141 - New scenarios for large_transaction_test (& w/ GC)

src/include/catalog/schema.h, src/include/common/typedefs.h, src/include/type/type_util.h
Fix #146.
Need these since SqlTable will be instantiated with Schema rather BlockLayout. This seems like the minimum functionality we need now, but happy to discuss if I overlooked something.
=> Added simple Column and Schema classes

benchmark/storage/garbage_collector_benchmark.cpp, benchmark/util/benchmark_main.cpp, script/micro_bench/run_micro_bench.py
Went after some low hanging fruit.
Fix #153.
=> Add benchmarks for GC unlinking and deallocating

src/transaction/transaction_manager.cpp
Race condition where a dependent commit is persistent before the commit it depends on, which will result in inconsistent state to the external world (or when we recover from log) if a crash happens immediately when the first commit is  written out but not the second one.  (More detail as comment in code)
By extending the critical section we rule this out from happening. This is overly strict and does not work if we go to serializable, but we can cross that bridge when we come to it.
Performance-wise, little to no impact (within margin of error) on low thread numbers because the global transaction table maintenance is the heavy-hitter, but some impact as we scale up (say, 16 threads). Again, can always fix later. Good numbers on incorrect software is useless.
Numbers from dev 4 with write …
=> Extend critical section in commit to fix race condition

src/include/storage/tuple_access_strategy.h
fix up documentation for private class to be not doxygen. The doxygen comment was out of date and not checked on CI-builds
=> Documentation cleanup

src/include/transaction/transaction_manager.h, src/transaction/transaction_manager.cpp
=> rename table latch

.travis.yml, Jenkinsfile, cmake_modules/CompilerInfo.cmake
Fixes #247.
@crd477 updated the Jenkins image (thanks Chad!), so we can open a PR to bump the Travis version as well.
This also includes a fix from #252.
=> Xcode10 for Travis and Jenkins, LLVM_DIR change for Homebrew

src/include/storage/block_layout.h, src/storage/block_layout.cpp
in the data table's layout. We now can ask the block layout whether a value is varlen or not.
We will implement all the logic in GC and logging in later PRs
=> Add varlen flag to block layout

script/installation/packages.sh
This resolves #279 
Signed-off-by: Yesheng Ma <kimi.ysma@gmail.com>
=> Update libz dependency in ubuntu install scripts

test/util/transaction_test_util.cpp
=> Fix cases where committed transactions may be empty

test/parser/parser_test.cpp
Added more unit tests to enhance existing code coverage for postgresparser.cpp
=> Adding more parser tests for coverage

src/include/type/transient_value.h
=> Fix strict aliasing warning on Release mode with TransientValue

script/github/github-pr-status.py, script/github/github-stats.py
These are the scripts we use to send out the daily PR czar emails and update the stats on the homepage.
The czar script can identify PRs that are waiting for review but is unable to identify when a PR has a review that needs a response.
=> Github PR Czar Scripts

test/parser/parser_test.cpp, test/storage/bwtree_test.cpp
Enhanced a few existing tests to reach more code / cases.
=> More parser test for coverage

src/storage/projected_row.cpp, test/common/object_pool_test.cpp, test/storage/delta_record_test.cpp, test/storage/storage_util_test.cpp, test/storage/tuple_access_strategy_test.cpp, test/util/transaction_test_util.cpp
This resolves current issues on master with gcc8. Note that this does not guarantee future gcc8 compatibility as we are currently not testing it in CI. This was just some quick low-hanging fruit.
=> GCC 8 fixes

src/include/storage/storage_util.h, src/storage/storage_util.cpp
@amlatyrngom pointed out that our padding calculation is insufficient, and is a non-trivial drag in some cases. Sure, it's not that much performance, but there's very little reason not to do some bit twiddling here.
=> Faster padding calculation

benchmark/storage/logging_benchmark.cpp, benchmark/transaction/large_transaction_benchmark.cpp, src/include/storage/garbage_collector_thread.h, test/storage/bwtree_index_test.cpp, test/storage/large_garbage_collector_test.cpp, test/storage/log_test.cpp
=> Add dedicated GC thread class for tests and main to use.

src/include/optimizer/operators.h
This is just a test of pushing things to this branch on the main repo. This still does not compile.
=> Compilation fixes for logical ops

src/include/loggers/optimizer_logger.h, src/include/optimizer/statistics/histogram.h, test/optimizer/histogram_test.cpp
This is the first step in porting over Peloton's optimizer statistics code (#436).
This is just the histogram + test cases for now.
=> Optimizer Stats: Histogram

src/CMakeLists.txt, src/include/loggers/loggers_util.h, src/include/loggers/optimizer_logger.h, src/include/optimizer/statistics/count_min_sketch.h, src/include/optimizer/statistics/histogram.h, src/loggers/optimizer_logger.cpp, test/optimizer/count_min_sketch_test.cpp, test/optimizer/histogram_test.cpp, third_party/madoka/approx.h, third_party/madoka/croquis.h, third_party/madoka/exception.h, third_party/madoka/file.cc, third_party/madoka/file.h, third_party/madoka/hash.h, third_party/madoka/header.h, third_party/madoka/madoka.h, third_party/madoka/random.h, third_party/madoka/sketch.cc, third_party/madoka/sketch.h, third_party/madoka/util.h, third_party/murmur3/MurmurHash3.cpp, third_party/murmur3/MurmurHash3.h, third_party/versions.txt
This brings over more of the Peloton optimizer. This is just the `CountMinSketch`. I added more test cases to prove that it behaves the way we expect it.
This also has a slightly modified version of Murmur3.
**Update:** I removed our custom implementation and replaced it with [madoka](https://github.com/s-yata/madoka). It is more accurate and much faster.
=> Optimizer Stats: CountMinSketch

src/include/loggers/optimizer_logger.h, src/include/optimizer/statistics/count_min_sketch.h, src/include/optimizer/statistics/histogram.h, src/include/optimizer/statistics/top_k_elements.h, test/optimizer/count_min_sketch_test.cpp, test/optimizer/histogram_test.cpp, test/optimizer/top_k_elements_test.cpp
This PR brings in the `TopKElements` class. I stripped out most of the internal architecture with the custom priority queue. I still need to re-enable the remaining test cases and add documentation for the functions.
I also refactored the `Histogram` and `CountMinSketch` APIs so that they use the same method names (`Increment`, `Decrement`, and `Remove`).
https://www.youtube.com/watch?v=Xvf1ObaJVVE
=> Optimizer Stats: Top-K Tracker

third_party/murmur3/MurmurHash3.cpp, third_party/murmur3/MurmurHash3.h
This brings in the original Murmur3 implementation instead of the janky hacked up Peloton version. 
This fixes #444
=> Real Murmur3

Jenkinsfile
simply updates the descriptive text in the macOS stages in Jenkins
=> update stage macos stage identifiers for mojave/xcode update

src/include/catalog/catalog_accessor.h
No idea why #486's CI runs didn't catch that there's a doxygen issue in it.
=> Fix doxygen for CatalogAccessor

src/include/storage/block_access_controller.h, test/storage/block_access_controller_test.cpp
=> Fix block access controller test

test/optimizer/count_min_sketch_test.cpp
This greatly reduces the probability of a spurious failures when testing our `CountMinSketch` (see #530). Since it's probabilistic data structure, there could still be issues. But I ran the test 250k times on my machine and did not hit an error.
* We reduce the # of heavy hitters and use exponentially larger numbers between them.
* Increase the width of sketches for the tests that are more sensitive to differences.
https://youtu.be/12M-PmtkVfU
=> CountMinSketch Tests Fixes

.clang-tidy, src/include/planner/plannodes/abstract_join_plan_node.h, src/include/planner/plannodes/abstract_plan_node.h, src/include/planner/plannodes/abstract_scan_plan_node.h, src/include/planner/plannodes/hash_plan_node.h, src/include/settings/settings_manager.h, src/settings/settings_manager.cpp
=> clang-tidy: performance-unnecessary-value-param

script/micro_bench/run_micro_bench.py
#516 changed some performance numbers so we want to reset the lookback to reflect that.
=> Update lookback after merging #516

.gitignore, src/include/common/hash_util.h, src/include/common/worker_pool.h
This is for #569 
https://youtu.be/DpYR3VXp-18
=> Add missing documentation for typedefs

test/common/thread_cpu_timer_test.cpp
Should get rid of false failures on Jenkins.
=> Simplified thread cpu timer test

test/common/thread_cpu_timer_test.cpp, test/execution/ast_dump_test.cpp
This is an attempt to boost our coverage numbers by targeting the one file with *zero* coverage.
https://youtu.be/xS1pDvb_6Hk
=> AstDump Unit Test

Jenkinsfile, README.md
this moves the doxygen check to the Check stages in Jenkins per #672 and also enables `parallelsAlwaysFailFast` for the entire Jenkins pipeline.
=> move doxygen to Jenkins

script/testing/junit/InsertTest.java, src/binder/bind_node_visitor.cpp
Fix #712. 
Was fixed by #768, regressed in #758, this adds a test so that we won't regress again.
=> Fix NULL regression, add simple test for inserting a single NULL int.

src/include/planner/plannodes/order_by_plan_node.h
=> Fix compiler_test by removing outdated assert after #762.

test/execution/thread_state_container_test.cpp
Sleep hack fix TBB memory leak with ASAN in debug mode for #819.
https://youtu.be/ywK-VFa4mIA
=> ASAN Leak Fix for ThreadContainerStateTest

Jenkinsfile, script/testing/util/constants.py, script/testing/util/test_server.py
I need to figure out why our Python testing stuff doesn't work correctly when compiling master branch. This is a mess...
https://youtu.be/SQQL6ev778I?t=124
=> Python Testing Junit Problems

src/include/execution/vm/bytecode_handlers.h
Caught running the junit tests in extended query mode.
=> Fix failed assertion when a NULL parameter comes in

src/include/storage/index/index_builder.h, src/storage/index/index_builder.cpp, util/execution/table_generator/table_reader.cpp
Oversight on my part when it was first written.
=> Move IndexBuilder definition to cpp

.dockerignore, Dockerfile
I changed the docker image to install the packages the same way that the build pipeline is installing the packages. I also added a step to copy the current directory into the docker image. That will help with local development. If this gets approved I will update the documentation here: https://github.com/cmu-db/terrier/wiki/Docker
=> Dockerfile update

script/testing/junit/traces/functions.test, src/catalog/database_catalog.cpp, src/execution/sema/sema_builtin.cpp, src/execution/vm/bytecode_generator.cpp, src/include/catalog/postgres/pg_proc.h, src/include/execution/ast/builtins.h
This PR was created by cherry picking the following commit: https://github.com/apavlo/terrier/commit/e13a2c3098c8a76eef15a6c649d3b39a9a964c73 and then manually resolving conflicts, updating certain sections, and converting the JUnit tests to SQL trace tests.
The original PR can be found here: https://github.com/apavlo/terrier/pull/4
This works towards resolving #1001
=> Hackathon hyperbolic trig functions

benchmark/storage/recovery_benchmark.cpp, src/include/main/db_main.h, src/include/settings/settings_callbacks.h, src/include/settings/settings_defs.h, src/settings/settings_callbacks.cpp, test/settings/settings_test.cpp, test/storage/log_test.cpp, test/storage/recovery_test.cpp
=> Standardize WAL Setting Parameter Names

build-support/check_github_labels.py
Unauthenticated rate-limit is 60 requests per hour. Authenticated would be 5000 per hour.
Web scraping like this is unlimited and Jenkins is too fragile for me to want to think about OAuth tokens, so...
=> Modify check_github_labels script to scrape the PR page if rate-limited.

Jenkinsfile
I just want to test and see if this works on Jenkins
=> Abort (instead of failing) builds that are not labeled "ready-for-ci".

src/include/main/db_main.h, src/include/settings/settings_defs.h, src/main/noisepage.cpp, test/messenger/messenger_test.cpp
Also fix a settings network port fuckup that came in the Messenger PR.
=> Disable messenger by default.

src/catalog/database_catalog.cpp
Fixes #1267 (for real this time...)
The root cause of #1267 was a rare race between an aborting transaction and the GC that could cause deferred abort actions to occur before the transaction is unlinked (see thread schedule in the changes).  The proper way to handle an implicit dependency between a deferred action (which conceptually unlinking is) and another deferred action is to double-defer the dependent action.
=> Fix use-after-free in DDL aborts

CMakeLists.txt
=> Upgrade fast_float to tagged release version.

Jenkinsfile, README.md, docs/README.md
Drop macOS support.
We foresee having to drop macOS support in the future for a variety of reasons.
In preparation of that, this PR removes the Mac builds from the Jenkins pipeline and updates our documentation accordingly.
=> Drop macOS support.

src/include/common/shared_latch.h
`tbb::reader_writer_lock` is deprecated. This PR replaces usage of `tbb::reader_writer_lock` with `std::shared_mutex`.
Closes [#1435](https://github.com/cmu-db/noisepage/issues/1435).
Per the discussion in [the associated issue](https://github.com/cmu-db/noisepage/issues/1435), preliminary results suggest that this refactor has a neutral or positive impact on performance. However, further investigation is still required. Submitting this PR now so we can see what CI reports for performance measurements.
Some of the reading that I did while looking into this (albeit briefly) suggests that spin locks are generally dangerous to performance if not used carefully. We currently use the `SpinLatch` type in quite a few locations throughout the codebase. Currently, `SpinLatch` just wraps …
=> Replace tbb::reader_writer_lock with std::shared_mutex.

script/self_driving/model_server.py
I accidentally left a print statement in there while I was testing #1526.
=> Remove print statement from model_server's _parse_msg.

src/replication/primary_replication_manager.cpp
Fix waiting for commit callbacks to be invoked by non-existent replicas.
If there are no replicas, but replication is synchronous, then replication will block indefinitely waiting for replicas to trigger the commit callback invocation. This adds a quick fix for that case.
This should pass CI without hitches.
=> Fix waiting for commit callbacks to be invoked by non-existent replicas.

docs/design_replication.md
Update design_replication doc to compare with Postgres streaming replication.
What it says on the can.
=> Update design_replication doc to compare with Postgres streaming replication.

src/include/main/db_main.h
Switch STORAGE_LOG_INFO to STORAGE_LOG_DEBUG for startup transaction policy message.
^
=> Switch STORAGE_LOG_INFO to STORAGE_LOG_DEBUG for startup transaction policy message.

src/planner/plannodes/abstract_join_plan_node.cpp, src/self_driving/modeling/operating_unit_recorder.cpp
Small fixes to explain json and tpl for chbenchmark q2.
Will allow #1598 to be reproduced with #1588.
=> Small fixes to explain json and tpl for chbenchmark q2.

docs/design_execution.md
This PR introduces a design document for the execution engine subsystem.
=> Execution Engine Design Document
