src/include/common/common_defs.h

I think it worked on Mac because we had an explicit stdlib=libc++.
This allows cmake to build on Ubuntu with gcc/g++ 7.

Include <cstddef> to use std::byte on Ubuntu.

---

src/util/string_util.cpp

Resolves an issue found by make check-clang-tidy.
../terrier/src/util/string_util.cpp:159:5: warning: Call to function 'strcpy' is insecure as it does not provide bounding of the memory buffer. Replace unbounded copy functions with analogous functions that support length arguments such as 'strlcpy'. CWE-119 [clang-analyzer-security.insecureAPI.strcpy]
strcpy(&formatted[0], fmt_str.c_str());
^

Replace unsafe call to strcpy in StringUtil

---

src/include/common/concurrent_bitmap.h
src/include/common/container/bitmap.h
src/include/common/spin_latch.h
src/include/storage/tuple_access_strategy.h
src/include/storage/varlen_pool.h
src/storage/tuple_access_strategy.cpp
test/common/bitmap_test.cpp
test/common/concurrent_bitmap_test.cpp
test/include/util/container_test_util.h
test/storage/tuple_access_strategy_test.cpp

We need a bitmap for our tuple buffers being passed around, but don't need it to be concurrent. This is  basically ConcurrentBitmap without the CAS.
Also removed UnsafeSet from ConcurrentBitmap and ran formatter.

Added bitmap and bitmap_test

---

.travis.yml
Dockerfile
script/installation/packages.sh

Addresses #31.
We now only support Ubuntu 18.04 and MacOS.
1. Simplifies and removes the packages installed by packages.sh to a bare minimum.
2. We are not using Brewfiles. We will specify version in brew install whenever possible.
3. Added a new machine to Travis that will install requirements via packages.sh instead of Dockerfile.

Packages cleanup, new Travis check

---

.travis.yml
CMakeLists.txt
Dockerfile
cmake_modules/Coveralls.cmake
cmake_modules/CoverallsClear.cmake
cmake_modules/CoverallsGenerateGcov.cmake
script/installation/packages.sh

1. Added coveralls.io support via [coveralls-cmake](https://github.com/JoakimSoderberg/coveralls-cmake). When we switch to Jenkins, we will need to modify [these](https://github.com/JoakimSoderberg/coveralls-cmake/blob/master/cmake/CoverallsGenerateGcov.cmake#L276-L277) in accordance with [this](https://docs.coveralls.io/api-introduction).
2. Switched Travis to fail fast if formatting/tidy/etc complained.
3. Added build-essential as a dependency - technically unnecessary, but it saves people from having to update-alternatives for gcc and g++. Also added a disclaimer to packages.sh.

Coveralls and other CI improvements

---

cmake_modules/SetupCxxFlags.cmake
cmake_modules/ThirdpartyToolchain.cmake
src/CMakeLists.txt

While profiling the new DataTable tests tonight, I realized that jemalloc was only linked against the terrier binary. This is probably a mistake. It should be linked to the terrier_shared library, otherwise we're using the system's native malloc for any other executables (Google Test, etc.)
In researching how we ended up with this behavior, I learned that Peloton also only links jemalloc against its executable, rather than the Peloton library. I'm not sure if this was intentional.
edit: [Related Peloton discussion](https://github.com/cmu-db/peloton/issues/220)

Modify jemalloc to be linked to the terrier_shared library

---

.clang-tidy
build-support/run-clang-tidy.sh
cmake_modules/FindTBB.cmake
src/include/common/container/concurrent_bitmap.h
src/include/common/json_serializable.h
src/include/storage/storage_defs.h

Fix #50.
1. Linux + clang + TBB = TBB cannot detect C++11 features.
We can manually tell TBB where the C++11 features are by setting -DTBB_USE_GLIBCXX_VERSION=V, where for gcc compiler version M.m.p, we have V = 10000 M + 100 m + p.
As a workaround, we know that clang-tidy reads the contents of compile_commands.json, which is itself generated by CMake. So we add the above TBB_USE_GLIBCXX_VERSION as a CXX flag.
2. The clang-tidy we modified from Arrow was pretty broken. We settled for bugprone, clang-analyzer, google, modernize, performance, portability, and readability checks. We also check header files now.

Clang tidy fixes

---

src/include/common/container/concurrent_bitmap.h

Previously forgot to account for starting at an offset.

Bugfix: bits_left should account for start_pos.

---

benchmark/include/util/storage_benchmark_util.h
benchmark/storage/data_table_benchmark.cpp
src/include/common/container/concurrent_bitmap.h
src/include/common/object_pool.h
src/include/storage/data_table.h
src/include/storage/storage_defs.h
src/include/storage/tuple_access_strategy.h
src/storage/data_table.cpp
src/storage/storage_defs.cpp
src/storage/tuple_access_strategy.cpp
test/include/util/storage_test_util.h
test/storage/tuple_access_strategy_test.cpp

Went from ~1M tuples/sec to ~14M tuples/sec on single-threaded insert. Still looking at a couple small tweaks before review, but we're ready to see how it does on CI.
At a high level:
- removed code related to concurrent schema. We can still support it, but the metadata structures aren't necessary at the moment
- optimized ObjectPool for BlockStore use
- optimized starting point for bitmap scan for Allocate
- aligned NullBitmaps to 64-bit and columns to their attribute sizes, yielding a large performance speedup (added a test case for this)
- the offsets for columns are now computed at TAS construction, rather than when initializing each RawBlock
- added simple DataTable insert tests

Data Table insert benchmarks and performance fixes

---

test/common/bitmap_test.cpp
test/common/concurrent_bitmap_test.cpp
test/include/util/container_test_util.h
test/storage/tuple_access_strategy_test.cpp

Fix #70.
1. Beefs up tests for bitmap, concurrent_bitmap and tuple_access_strategy. Mainly tweaks number of iterations, bitmap sizes tested, number of columns in layouts generated.
2. Changed from `std::bitset<N>` to `std::vector<bool>` for dynamic bitsets. (`vector<bool>` still specialized in C++17, §26.3.12).
On my laptop,
```
make unittest
Start 1: bitmap_test
1/7 Test #1: bitmap_test ......................   Passed   45.40 sec
Start 2: concurrent_bitmap_test
2/7 Test #2: concurrent_bitmap_test ...........   Passed   44.39 sec
Start 3: object_pool_test
3/7 Test #3: object_pool_test .................   Passed    0.29 sec
Start 4: data_table_concurrent_test
4/7 Test #4: data_table_concurrent_test .......   Passed    1.98 sec
Start 5: data_table_test
5/7 Test #5: data_table_test …
```

Beef up tests for bitmap, concurrent bitmap and tuple access strategy

---

src/include/common/container/concurrent_bitmap.h
src/include/storage/tuple_access_strategy.h
test/common/concurrent_bitmap_test.cpp

1. Aligns atomic loads. (Assumes byte 0 is aligned for 64-bit loads)
2. Now respects the starting position. (Previously might have returned a position < start_pos, added some tests for that)
My laptop is pretty terrible for benchmarking. I ran it a few times and picked the runs with the lowest variance. 
Before:
BM_SimpleInsert/repeats:10/real_time_mean              204 ms        204 ms          3   9.80427MB/s
BM_SimpleInsert/repeats:10/real_time_median            202 ms        201 ms          3   9.90511MB/s
BM_SimpleInsert/repeats:10/real_time_stddev              7 ms          6 ms          3   331.179kB/s
BM_ConcurrentInsert/repeats:10/real_time_mean           98 ms          0 ms          7   20.3687MB/s
BM_ConcurrentInsert/repeats:10/real_time_median         98 ms          0 ms …

Concurrent Bitmap speedup

---

test/storage/data_table_concurrent_test.cpp

Add comments for concurrent data table tests.

---

src/include/common/spin_latch.h

Fix #83 
Replace our spin_latch implementation with TBB's. Skylake and newer processors increase the PAUSE latency by an order of magnitude, so efficient spinning requires more work. Intel handles this for us in their spin_mutex with tbb::internal::atomic_backoff.
References:
https://software.intel.com/en-us/articles/a-common-construct-to-avoid-the-contention-of-threads-architecture-agnostic-spin-wait-loops
https://github.com/01org/tbb/blob/tbb_2018/include/tbb/spin_mutex.h
https://github.com/01org/tbb/blob/tbb_2018/include/tbb/tbb_machine.h

Update spin_latch to use TBB spin_mutex

---

src/include/common/rw_latch.h

We'll use this in the transaction manager.
References:
https://software.intel.com/en-us/node/506280

Adds a rw_latch implementation that wraps TBB's

---

Dockerfile
cmake_modules/ThirdpartyToolchain.cmake
script/installation/packages.sh

Adds Boost filesystem as a required dependency for @aaron-tian's logging. Adds the package to the automation scripts.
Eventually we want to look into replacing this with C++17's native filesystem library, but Clang support isn't there yet.

Boost filesystem

---

CMakeLists.txt
benchmark/include/util/storage_benchmark_util.h
build-support/run_clang_format.py
test/include/util/storage_test_util.h

We now format benchmark, src, and test. Codebase fixed accordingly.

Enable clang-format on benchmark and test

---

src/include/storage/data_table.h
src/include/storage/storage_defs.h
src/storage/data_table.cpp
test/storage/data_table_concurrent_test.cpp
test/transaction/mvcc_test.cpp

This is based on the scenario described in Slack last night that @tli2 found with his large scale randomized concurrency control tests.
I extended the logic for HasConflict(), and added a test case for the scenario. I also had to make a change in the concurrent DataTable test that was violating this new constraint.
I also fixed an unrelated comment in DeltaRecord that @yangjuns asked me about this morning.

Extended first writer wins logic for HasConflict

---

benchmark/include/util/storage_benchmark_util.h
benchmark/storage/data_table_benchmark.cpp
benchmark/storage/tuple_access_strategy_benchmark.cpp
cmake_modules/FindClangTools.cmake

Refactored the DataTable and TAS benchmarks to use fixtures. We might want to consolidate these once we have an idea of what our long-term benchmark workloads are going to be.
Note the DataTable benchmarks aren't using really beginning and committing transactions. We just want to test DataTable performance. We should add a TransactionManager benchmark this week to test that.

Benchmarks refactor

---

src/include/common/typedefs.h
src/include/loggers/transaction_logger.h
src/include/storage/data_table.h
src/include/storage/garbage_collector.h
src/include/storage/storage_defs.h
src/include/transaction/transaction_context.h
src/include/transaction/transaction_manager.h
src/loggers/transaction_logger.cpp
src/main/terrier.cpp
src/storage/garbage_collector.cpp
test/include/util/test_harness.h
test/storage/garbage_collector_test.cpp
test/transaction/large_transaction_test.cpp
test/transaction/mvcc_test.cpp

Fix #110.
This is a simple garbage collector for the storage layer that will unlink obsolete versions from version chains and then free TransactionContexts once no one else can hold a reference to them.
There are also a few API changes to support GC, as well as minor bug fixes.

Garbage Collection

---

CMakeLists.txt
cmake_modules/SetupCxxFlags.cmake
cmake_modules/ThirdpartyToolchain.cmake
cmake_modules/san-config.cmake

Explicitly setting the policy to NEW to silence the warning about rpath stuff.
It resolves this warning in master:
```
CMake Warning (dev):
Policy CMP0068 is not set: RPATH settings on macOS do not affect
install_name.  Run "cmake --help-policy CMP0068" for policy details.  Use
the cmake_policy command to set the policy and suppress this warning.
For compatibility with older versions of CMake, the install_name fields for
the following targets are still affected by RPATH settings:
terrier_shared
This warning is for project developers.  Use -Wno-dev to suppress it.
```

Fix CMP0068 CMake warning on Mac

---

src/include/loggers/storage_logger.h
src/include/loggers/transaction_logger.h

Specifically for WARN. Storage logger has a typo, and that multiplied to the transaction logger when that file was copy and pasted.

Fix typo in the storage and transaction logger macro definitions

---

build-support/run-test.sh

Per https://github.com/apache/arrow/pull/2443 , note the usage of shift.
I thought it might have disabled ASAN in tests, but it looks like everything was still running properly. We should probably still fix it though.

Revert to arrow behavior in run-test.sh

---

benchmark/storage/data_table_benchmark.cpp
benchmark/storage/tuple_access_strategy_benchmark.cpp
test/common/concurrent_bitmap_test.cpp
test/common/object_pool_test.cpp
test/include/util/multi_threaded_test_util.h
test/include/util/random_test_util.h
test/include/util/storage_test_util.h
test/include/util/test_thread_pool.h
test/storage/data_table_concurrent_test.cpp
test/storage/tuple_access_strategy_test.cpp
test/storage/varlen_pool_test.cpp
test/util/transaction_test_util.cpp

Fix #102.
To use RunUntilThreadsFinish, we now need to construct an instance of MultiThreadedTestUtil. The tests have been fixed up accordingly. All other functionality remains the same.
Not implemented: shutting down a subset of threads. Would we want this?

Add thread pool to Google Tests to avoid constant creation and reaping of threads

---

src/include/storage/garbage_collector.h
src/include/transaction/transaction_defs.h
src/include/transaction/transaction_manager.h
src/storage/garbage_collector.cpp
src/transaction/transaction_manager.cpp

By default the std::queues were backed by std::dequeue which I believe to be inefficient for the GC's use case. Also added basic TRACE logging to GC to be able to watch its state.

Define TransactionQueue to be backed by std::list, add TRACE logging to GC

---

src/include/storage/garbage_collector.h
src/storage/garbage_collector.cpp
test/storage/garbage_collector_test.cpp
test/transaction/mvcc_test.cpp

Adapted the MVCC tests to basic GC tests. Also added an optimization to GC that allows it to deallocate a read-only txn in a single pass.

Add small-scale GC tests and optimization for read-only txns

---

CMakeLists.txt
benchmark/storage/data_table_benchmark.cpp
benchmark/storage/tuple_access_strategy_benchmark.cpp
benchmark/util/benchmark_main.cpp
build-support/run_clang_format.py
src/loggers/main_logger.cpp
src/loggers/storage_logger.cpp
src/loggers/transaction_logger.cpp
src/main/terrier.cpp
src/storage/data_table.cpp
src/storage/delta_record.cpp
src/storage/garbage_collector.cpp
src/storage/storage_util.cpp
src/storage/tuple_access_strategy.cpp
src/transaction/transaction_manager.cpp
test/common/bitmap_test.cpp
test/common/concurrent_bitmap_test.cpp
test/common/object_pool_test.cpp
test/storage/data_table_concurrent_test.cpp
test/storage/data_table_test.cpp
test/storage/delta_record_test.cpp
test/storage/garbage_collector_test.cpp
test/storage/large_garbage_collector_test.cpp
test/storage/projected_row_test.cpp
test/storage/storage_util_test.cpp
test/storage/tuple_access_strategy_test.cpp
test/storage/varlen_pool_test.cpp
test/transaction/large_transaction_test.cpp
test/transaction/mvcc_test.cpp
test/util/transaction_test_util.cpp

Part of #105. 
Comments:
1. There is a reference to .cc files in [asan_symbolize.py](https://github.com/cmu-db/terrier/blob/master/build-support/asan_symbolize.py#L27), but I'm not sure if it should be changed.
2. I tried making cpplint Python-3 compatible. It mostly involves removing references to unicode, iteritems, itervalues. But I do not think this is worth doing; most systems will have Python 2 as the default env python. At most a mild inconvenience for people like me who have a Python 3 default.
Whenever we're ready, we can rebase and run make format.

Fix clang-format for .cpp files

---

test/common/bitmap_test.cpp
test/common/concurrent_bitmap_test.cpp
test/storage/data_table_concurrent_test.cpp
test/storage/data_table_test.cpp
test/storage/delta_record_test.cpp
test/storage/large_garbage_collector_test.cpp
test/storage/projected_row_test.cpp
test/storage/storage_util_test.cpp
test/storage/tuple_access_strategy_test.cpp
test/transaction/large_transaction_test.cpp

... so that test runtime makes more sense. Reduction is applied overboard for CI tests (we can run longer tests overnight), especially on easier things like bitmaps. Large tests run time is slightly increased.

tweak test numbers

---

test/storage/garbage_collector_test.cpp
test/transaction/mvcc_test.cpp

Make num_iterations for garbage_collector_test and mvcc_test consistent since they represent the same test sequences.

num_iterations adjustment on mvcc and gc tests

---

src/include/common/scoped_timer.h

This is more of a debugging tool at the moment, but eventually we might want to use this performance profiling of various components at runtime in the complete system. I decided to throw this together while trying to time each stage of the garbage collection process. We should prefer to use Google Benchmarks when actually characterizing performance, and also avoid using this as some sort of Google Test pass/fail metric. I just think it's useful for debugging and comparing performance changes for aspects of the system that don't have full benchmarks. I'm happy to not merge it in if others don't think it'll prove useful though.
```
#include <iostream>
#include <thread>  // NOLINT
#include "common/scoped_timer.h"
int main() {
uint64_t elapsed_ms = 0;
{
terrier::common::ScopedTimer …
```

ScopedTimer

---

src/include/transaction/transaction_defs.h
src/storage/garbage_collector.cpp
src/transaction/transaction_manager.cpp
test/storage/large_garbage_collector_test.cpp

This is a performance change and should reduce the time needed to move elements between TransactionQueues. I modified the large_garbage_collector__test to behave as a benchmark (not kept in this PR, but we should probably add a scenario like this as a dedicated benchmark in the future) by creating a large table, running a bunch of update transactions, and then seeing how long the GC takes to clean up all the garbage.
```
#include <chrono>
#include <vector>
#include "gtest/gtest.h"
#include "storage/garbage_collector.h"
#include "util/transaction_test_util.h"
namespace terrier {
class LargeGCTests : public TerrierTest {
public:
storage::BlockStore block_store_{1000};
common::ObjectPool<storage::BufferSegment> buffer_pool_{1000};
std::default_random_engine generator_; …
```

 Switch TransactionQueue from a std::queue to a std::forward_list. 

---

src/include/common/container/concurrent_bitmap.h

Added to class header and to the function that assumes this.

Document and enforce the alignment assumption in RawConcurrentBitmap.

---

.travis.yml

This (hopefully) fixes the current build issues on Travis with macOS since LLVM 7's release yesterday.

Update LLVM_DIR path for LLVM@6 after LLVM 7's release

---

src/include/storage/garbage_collector.h
src/include/storage/undo_record.h
src/storage/data_table.cpp
src/storage/garbage_collector.cpp
src/transaction/transaction_manager.cpp
test/storage/garbage_collector_test.cpp

The new GC tests (#167) demonstrated an issue with the GarbageCollector contending with a txn trying to perform an abort on the same slot. This extends our first writer wins semantics to the GC. Basically if the GC needs to update an uncommitted UndoRecord's next pointer in order to unlink the garbage UndoRecord, it will defer and requeue that txn's context for the next GC invocation.
We avoid processing UndoRecords multiple times by applying a new invariant: if an UndoRecord's table pointer in null, that means it is not installed in a version chain. We apply this to write-write conflicts at the DataTable and TransactionManager level, as well as the GarbageCollector.
I added a simple test case for this, but the real proof is once the new GC tests go in after this. I have verified locally …

Fix for GC contending with TM's Rollback()

---

test/storage/large_garbage_collector_test.cpp
test/transaction/large_transaction_test.cpp

I noticed a failure while running the tests. Here is the corresponding log:
> Running main() from gtest_main.cc
[==========] Running 5 tests from 1 test case.
[----------] Global test environment set-up.
[----------] 5 tests from LargeGCTests
[ RUN      ] LargeGCTests.MixedReadWriteWithGC
[       OK ] LargeGCTests.MixedReadWriteWithGC (12383 ms)
[ RUN      ] LargeGCTests.HighAbortRateWithGC
/home/amlatyr/Code/terrier/test/util/transaction_test_util.cpp:246: Failure
Value of: StorageTestUtil::ProjectionListEqual(layout_, entry.second, it->second)
Actual: false
Expected: true
[  FAILED  ] LargeGCTests.HighAbortRateWithGC (7657 ms)
[ RUN      ] LargeGCTests.HighAbortRateHighThreadWithGC
[       OK ] LargeGCTests.HighAbortRateHighThreadWithGC (7041 ms)
[ RUN      ] LargeGCTests.TPCCWithGC
[ …

#141 - New scenarios for large_transaction_test (& w/ GC)

---

src/include/transaction/transaction_manager.h
src/transaction/transaction_manager.cpp

They don't really need to hold latches when committing. This brings our readonly performance from 600 to 770 k txns / s on 8 threads on dev 4 (same benchmark as #220)
Some performance degradation still happens at higher thread counts( > 10), but overall not as severe.

read-only transaction optimization

---

src/include/transaction/transaction_manager.h
src/transaction/transaction_manager.cpp

It's slower for us to always maintain this as an ordered data structure just so the GC can quickly ask who the oldest running txn is. We can maintain this as an unordered set and then let the GC scan quickly for the smallest value (it's typically a small set anyway) when it needs it. It also doesn't need to be a map at all that stores TransacationContext pointers. We had this in case we eventually extended to serializable following the HyPer model.
We still might eventually replace this with something else that scales better, but for now I saw minor performance gains from this on dev4 and an AWS instance with a large number of workers (16).

Replace running_txns map with unordered_set

---

src/main/terrier.cpp

This probably won't live for long in the codebase as we replace this with proper main behavior, but it's bothersome that it fails right now.

Fix assertion failure in Terrier main

---

build-support/run-clang-tidy.py

It turns out that having this enabled is pretty useful because people may be running different versions of clang-tidy, and we're using "give us all your checks" e.g. bugprone- instead of manually specifying all the checks that we're running. @tanujnay112 and I wasted some time on this.
@tli2 @mbutrovich should be a simple merge? And happy new year!
EDIT: We might want to discuss whether we should be explicitly listing the checks we want. If we do,
Pros: wouldn't waste time like this, guaranteed same checks regardless of platform or version
Cons: upgrading versions of clang-tidy would probably break (e.g. bugprone-macro-parentheses in this scenario), but this is autofixable and we probably would want to look at it anyway

List checks when invoking make check-clang-tidy.

---

src/include/parser/expression/aggregate_expression.h
src/parser/postgresparser.cpp

e.g. SELECT COUNT(DISTINCT id) FROM foo;
Quick fix for @DarkForte's tests. Note that aggregate expressions are still pretty broken, e.g. I don't think we're using root->agg_filter yet.

Add parser support for DISTINCT in aggregation functions.

---

src/include/common/container/concurrent_bitmap.h
src/include/storage/tuple_access_strategy.h
test/storage/data_table_test.cpp
test/transaction/mvcc_test.cpp

Insert wrap-around behavior is not changed even though the corresponding GC change went in. A simple test case is added so the wrap-around behavior is specified.

Insert patch

---

test/storage/bwtree_test.cpp

The bwtree tests assume an even number of threads, particularly the ConcurrentMixed test's logic. This forces the `num_threads_` variable to be even for that test suite.
This resolves the other issue reported by @pervazea in #264 when running the bwtree tests with 1 thread in a VM, which I reproduced.

Fix bwtree tests for odd numbered hardware_concurrency()

---

src/include/parser/expression/type_cast_expression.h
src/include/parser/expression_defs.h
src/parser/postgresparser.cpp
test/parser/parser_test.cpp

As discussed in #292 merging the CAST() operator with the ExpressionType::OPERATOR_CAST.
All `OPERATOR_*` operators are treated as AbstractExpressions which are handled as `T_A_Expr` by `AExprTransform()`, while CAST() was being handled separately as T_TypeCast under TypeCastTransform.
In order to make all cast operations use OPERATOR_CAST() we need to make the casting operation of the AbstractExpression type - which is what is being done here.
So now a casting operator goes through AExprTransform() where it gets triaged to the existing TypeCastTransform() there by reusing the existing code.

Merge CAST() and ExpressionType::OPERATOR_CAST

---

CMakeLists.txt
src/storage/block_layout.cpp
src/storage/storage_util.cpp
test/include/util/storage_test_util.h

While working on index stuff, we spotted a bug introduced in the code related to BlockLayouts introduced by VARLEN stuff. If the value of NUM_RESERVED_COLUMNS is changed from 1 to 2, the system dies. This fixes the bug and verified it works again with arbitrary NUM_RESERVED_COLUMNS.

NUM_RESERVED_COLUMNS fix

---

.travis.yml
CMakeLists.txt
build-support/bad_words.txt
src/include/common/performance_counter.h
src/include/parser/sql_statement.h
src/include/type/transient_value_peeker.h
src/main/terrier.cpp
test/common/stat_registry_test.cpp
test/include/util/bwtree_test_util.h
test/include/util/storage_test_util.h
test/storage/sql_table_test.cpp

This uses a blacklist of regex in build-support/bad_words.txt.
By carefully picking regex, we don't need to // NOLINT innocuous uses too much, e.g. schema.h had a variable called inlined_ that we were picking up.
As a general rule of thumb, if the word is standalone, use the word boundary regex,
\bWORD\b   e.g. \binline\b
if the word is part of a function, include the calling paren in the regex,
func(            e.g. malloc(
Also added this check to CI and fixed up all existing files.
NB: I didn't think it was worth porting over the old validator script. That's a lot of Python, the include-what-you-use and namespace-closing functionality has been subsumed by check-lint, we basically just want to run an intelligent grep. And grep is pretty fast.
It is also much easier to understand how the …

Bad words filter as "make check-censored" target

---

cmake_modules/ThirdpartyToolchain.cmake

Right now, CMake just picks some version of LLVM. This is annoying when you have old versions and it picks that, e.g. the dev machines. This specifies that we want to find a LLVM-6.0 compatible package.

LLVM CMake

---

Dockerfile
cmake_modules/ThirdpartyToolchain.cmake
script/installation/packages.sh

`boost filesystem` dependency was introduced last summer based on a perceived need for it for logging. It was never used.
Discuss bringing boost back in the future as needed.

Remove boost from build infrastructure

---

benchmark/storage/garbage_collector_benchmark.cpp

This new test supports #325 as a positive change, despite performance regressions on existing GC benchmarks, which strictly evaluate the GC's unlink and reclaim performance in isolation (i.e. no concurrent transactions). While this is useful for spotting regressions in the core GC algorithms, they doesn't properly evaluate how well the GC runs at the same time as the real system, particularly in high contention workloads from transactions. This PR adds a benchmark for that. On master the GC can clean up ~50k txns/second in this update-heavy workload. #325 increases that by an order of magnitude to ~500k txns/second on my laptop.

GC contention benchmark

---

script/micro_bench/run_micro_bench.py

Set benchmark failure threshold back to 10% after temporarily relaxation to 15%. Also set a new high watermark due to GC refactoring and merging in known performance "regression" on existing benchmarks that's actually faster in real workloads (already merged in a new becnhmark to reflect this).

Update benchmark lookback and threshold

---

src/storage/data_table.cpp
test/storage/large_garbage_collector_test.cpp

Updates were too conservative from before, and immediately return false when compare-and-swap fail on the version chain. The failure could be an innocuous one from the GC. In this PR we changed updates to retry on a CAS failure and only abort after seeing an actual conflict.

Updates now retry on failure

---

src/include/storage/storage_defs.h
test/storage/varlen_entry_test.cpp

I knew there was a reason we went with C++17. I found myself relying on [std::string_view](https://en.cppreference.com/w/cpp/string/basic_string_view) for some of the TPC-C implementation, and @tli2 suggested just adding an accessor to VarlenEntry since this is probably something we can use elsewhere in the system (catalog?).
Given a byte buffer (not necessarily null-terminated) and a length as arguments (which is basically what a VarlenEntry is) a std::string_view presents a zero-copy, immutable view that provides access to STL string functions (compare, find, etc.). It's awesome.

Add std::string_view accessor for VarlenEntry

---

src/include/storage/index/bwtree_index.h
src/include/storage/index/index.h
src/include/storage/index/index_metadata.h
test/storage/bwtree_index_test.cpp

**ProjectedRow Initializer accessor:**
We need a way to get the index's PR initializer without having access to the metadata object (similar to how it works DataTable).
**Index range scan:**
I added a basic range scan to the BwTree wrapper and a simple functionality test. We need this for some of the remaining TPC-C queries. Peloton's Scan function took in a (complicated to me) ConjugateScanPredicate object that looks like it was constructed in the Planner. Peloton's Scan method just extracted the low and high keys from that object, so as long as those are defined we can do range scans. I changed the Scan arguments to just take the low and high keys directly. I'm punting on understanding the 2000 lines of code of index scan plan nodes, index scan executors, and the scan optimizer stuff …

BwTreeIndex::Scan and PRI accessor.

---

script/micro_bench/run_micro_bench.py

Merging #324 threw off some of the low level numbers, so master is failing on Jenkins. Numbers still seem reasonable.

Update lookback on benchmarks

---

src/include/catalog/schema.h
test/include/util/catalog_test_util.h
test/storage/sql_table_test.cpp

@lmwnshn and I realized that we needed this information while constructing TPC-C schemas. This cherry-picks the change out of the TPC-C branch. Also got rid of the inlined field in the Column object since I'm not sure it has any meaning at this level. SQL level shouldn't know anything about attributes being inlined in the storage layer or not, as best as I can tell.

Add another Column constructor with a field for max VARLEN length

---

benchmark/storage/data_table_benchmark.cpp
src/include/storage/garbage_collector.h
src/include/storage/storage_defs.h
src/include/transaction/transaction_context.h
src/include/transaction/transaction_defs.h
src/include/transaction/transaction_manager.h
src/storage/garbage_collector.cpp
src/transaction/transaction_manager.cpp
test/common/stat_registry_test.cpp
test/storage/data_table_concurrent_test.cpp
test/storage/data_table_test.cpp
test/transaction/deferred_actions_test.cpp

This is an implementation of the epoch-based callback framework discussed during the meeting today and is a superset of the abort callbacks that #351 implements.  The framework allows the database to register callbacks into a transaction context to execute at either abort or commit (commit callbacks are currently disallowed in read-only transactions).  Additionally, deferred callbacks can be registered with the TransactionManager which will execute once all currently active transactions have exited (same logic as cleaning up undo records).
In order to allow the specific use case of cleaning up arbitrary side-effects within the system (temporary constraints, staged-then-aborted schema versions, etc.), I had to expose  the transaction manager to the storage layer through the transaction …

Add action framework

---

src/storage/data_table.cpp

As @pervazea pointed out, we might not want to copy the content of a tuple when it is already unallocated. This shouldn't be critical to correctness or performance in the common case.

Add short circuit on Select

---

src/include/common/gate.h

The new gate header has intermittent problems with doxygen.  This should fix the problem by more closely mimicking the other files for `DISALLOW_COPY_AND_MOVE` macro.

Fix doxygen problem

---

build-support/run-clang-tidy.py

clang-tidy can be so slow that Travis kills us while waiting for our progress bar to update.
This just prints stuff to stdout every 300 seconds (half Travis timeout) so that we don't get killed.

clang-tidy heartbeat

---

.travis.yml
Jenkinsfile

#378 avoids getting killed by Travis for no output being printed for 10 minutes. Instead it now gets killed for exceeding the maximum job duration.
Move clang-tidy to Jenkins.

Move clang-tidy to Jenkins

---

src/include/planner/plannodes/insert_plan_node.h
src/planner/plannodes/insert_plan_node.cpp
test/planner/plan_node_json_test.cpp

This PR changes how bulk inserts are represented in `InsertPlanNode`. Particularly, it makes the following changes:
* Change to `values_`
* Values is now a vector of vectors. This represents a list of "tuples" to insert, where each tuple is a vector of the values for that tuple.
* Change to `parameter_info_`
* Maps the index of a value to which column that value should be inserted into
* This could have been a `std::vector`, but I wanted the mapping to be explicit
* The `paramater_info_` allows for default values to be added during binding (in which case they would be in the `values_` vector and in `parameter_info`), or during execution (In which case there would be no entry for that column in `parameter_info`).
* Bulk insert count
* This is now simply the size of `values_`

Fix bulk insert for InsertPlanNode

---

script/micro_bench/run_micro_bench.py

We've refactored a number of benchmarks and also have the TPC-C microbenchmark. Need a new baseline build number now that we got a good run last night (CI issues previous days).

Update benchmark lookback

---

src/include/parser/expression/default_value_expression.h
src/include/settings/settings_manager.h
src/include/type/transient_value_factory.h
src/settings/settings_manager.cpp
test/type/transient_value_test.cpp

The whole point was not being able to easily copy TransientValues. If this is needed in the future we can discuss who gets access to the copy constructor.

Removed GetCopy() from TransientValueFactory

---

benchmark/storage/logging_benchmark.cpp

The logging benchmark was missing a call to `unlink` to delete the log file. 
I discovered this after trying to install a game and discovering I was out of memory on my laptop because there was a 23GB log file ¯\_(ツ)_/¯

Add missing unlink for LoggingBenchmark

---

benchmark/integration/tpcc_benchmark.cpp

Make it consistent with the other logging benchmarks. Also don't want to trash the disks in the benchmark machines (assuming they're SSDs).

Switch TPC-C microbenchmark for CI runs to use ramdisk

---

src/include/storage/write_ahead_log/log_record.h
src/include/transaction/transaction_manager.h
src/storage/write_ahead_log/log_serializer_task.cpp
src/transaction/transaction_manager.cpp
test/storage/log_test.cpp

We never actually set the log_processed flag on the abort code path, so it will be missed by garbage collector.

Abort Record Fix

---

src/include/transaction/transaction_context.h
src/storage/data_table.cpp
src/storage/garbage_collector.cpp
src/transaction/transaction_manager.cpp

Found that the metrics PR was using `TxnId()` as a unique identifier for a transaction (not unreasonable given the function name). You can't do that because that value actually changes at completion. 
Rename `TransactionContext::TxnId()` to `FinishTime()` with some comments about what it means under current MVCC semantics. Also added a comment that `StartTime()` can be used as a unique identifier for a transaction. Removed the reference accessor since classes that used it were already friends of `TransactionContext`. Added some stronger warnings to `TransactionContext`'s constructor and destructor for funsies after some recent instances of `TransactionContext`s getting manually deleted. I'm still considering making the destructor private but that sounds like a nightmare to refactor.

Rename TransactionContext::TxnId() to FinishTime()

---

CMakeLists.txt
cmake_modules/FindGTest.cmake
cmake_modules/ThirdpartyToolchain.cmake
src/include/common/macros.h
test/include/util/test_harness.h

This PR adds gmock to our cmake tool chain (apparently gmock is a superset of gtest, so their doc recommends search and replace)
Also adds a macro (FAKED_IN_TEST) to inject polymorphism needed to make mocks work. An example of how this would work in practice is shown in `access_observer_test` in #377

Add GMock and associated macro

---

benchmark/integration/tpcc_benchmark.cpp
benchmark/storage/bwtree_benchmark.cpp
benchmark/storage/garbage_collector_benchmark.cpp
benchmark/storage/logging_benchmark.cpp
benchmark/transaction/large_transaction_benchmark.cpp
src/include/common/scoped_timer.h

We need an easy way to change the resolution for different metrics, so implemented the TODO that's been sitting in ScopedTimer for a while.

Templatize ScopedTimer

---

src/storage/write_ahead_log/disk_log_consumer_task.cpp

Resolves #448 
This PR resolves the problems with the timeout described in #448. Instead of completely relying on the timeout feature of `std::condition_variable::wait_for`, we keep a timestamp of the last time we persisted. When we decide if we should persist, we simply check if the time elapsed since that timestamp is larger than the persist interval. We still make use of the timeout on `std::condition_variable::wait_for` to ensure we break out of the wait if the interval has passed.
I made special care to not conflict with the changes in #439, it should be a clean merge (besides some simple formatting fixes).

Fix to log persist timeout

---

src/include/loggers/catalog_logger.h
src/include/loggers/index_logger.h
src/include/loggers/main_logger.h
src/include/loggers/network_logger.h
src/include/loggers/parser_logger.h
src/include/loggers/settings_logger.h
src/include/loggers/storage_logger.h
src/include/loggers/test_logger.h
src/include/loggers/transaction_logger.h

This fix allows you to output objects in log messages. This fixes #458
I don't think a review is really necessary but we should follow the rules.

Include 'fmt/ostr.h' in all logger header files

---

src/include/common/managed_pointer.h
test/common/managed_pointer_test.cpp

I've had this in my metrics branch but people need this sooner than whenever that'll merge.
Fix #424, maybe not everything? Not clear about the casting stuff.

unique_ptr and nullptr support for ManagedPointer

---

src/catalog/catalog_accessor.cpp
src/catalog/database_catalog.cpp
src/include/catalog/catalog_accessor.h
src/include/storage/storage_defs.h
test/catalog/catalog_test.cpp

This PR fixes type sensitivity for catalog items (naming objects and fetching objects by name) by forcing all user-defined input strings to lowercase before proceeding.  To avoid copying the string into an intermediary value, I opted to make the internal varlen field `contents_` mutable but this should not be too risky as the getter methods only expose immutable views.

Normalize catalog names

---

src/include/type/transient_value.h
test/parser/expression_test.cpp

As found by @jrolli, we don't correctly serialize/deserialize out null `TransientValue`.

Fix to null TransientValue serialization

---

src/include/planner/plannodes/insert_plan_node.h
src/planner/plannodes/drop_trigger_plan_node.cpp
src/planner/plannodes/drop_view_plan_node.cpp
src/planner/plannodes/insert_plan_node.cpp
test/planner/plan_node_json_test.cpp

This commit tries to fix #427
1. Change parameter_info_ from `std::unordered_map<uint32_t /* value index */, catalog::col_oid_t>` to `std::vecto\<catalog::col_oid_t\>`
2. Change method signature AddParameterInfo from` Builder &AddParameterInfo(uint32_t value_idx, catalog::col_oid_t col_oid)` to `Builder &AddParameterInfo(catalog::col_oid_t col_oid)`. We rely on the caller to push col idx in order.
3. Fix hash function in src/planner/plannodes/drop_view_plan_node.cpp. From my understanding, we should calculate hash on the value (`! view_oid `) instead of on the address (`& view_oid`).

Switch InsertPlanNode.parameter_info to use std::vector

---

src/catalog/catalog.cpp
src/catalog/catalog_accessor.cpp
src/catalog/database_catalog.cpp
src/include/catalog/catalog.h
src/include/catalog/catalog_accessor.h
test/catalog/catalog_test.cpp

Updates the accessor to correctly handle the implicit placement of `pg_catalog` namespace in the search path when it is not explicitly set.  Specifically, PostgreSQL will always search `pg_catalog` first when resolving an unqualified object name unless `pg_catalog` was explicitly placed somewhere in the search path.  For unqualified object creation, the default namespace that is used is the first namespace in the explicit path.
Fixes #473

Search path fix

---

Jenkinsfile

This uses the new CMake flag to dynamically link jemalloc only for the benchmark build on Jenkins. Assuming the numbers make sense and it appears to be working correctly, we'll update the nightly build pipeline and reset the benchmark lookback next week.

Jenkins: Enable jemalloc for benchmark build on Jenkins

---

src/catalog/database_catalog.cpp
test/catalog/catalog_test.cpp

This PR contains the fix (as described by @jrolli on Slack) to `DatabaseCatalog::GetIndexes`. An additional test case has been provided to verify that `CatalogAccessor::GetIndexes` now works correctly.

Fix to CatalogAccessor's GetIndexes

---

script/micro_bench/run_micro_bench.py

We want to reset the lookback threshold due to enabling jemalloc on the benchmark runs. Any PRs in the next few weeks should have their benchmark numbers inspected manually to look for anomalies because they automatic regression failure won't trigger again until we have 10 nightly runs.

Reset benchmark lookback due to jemalloc being enabled

---

script/micro_bench/run_micro_bench.py

This enables the bwtree_benchmark suite to run as part of the nightly performance tests. We previously did not run them as it's exercising "third party" code with benchmarks that aren't ours either. However, we want to watch for any regressions on this data structure in the future, and in preparation for running the same tests against the hash index, we should enable this.

Add bwtree_benchmark to the nightly suite

---

src/catalog/database_catalog.cpp

We were passing the wrong schema for the pg_namespace index on the name column during bootstrapping. This meant that using `CatalogAccessor::GetIndexSchema` and getting the schema from the index's metadata gave two different schemas.

Fix to pg_namespace index

---

src/include/catalog/schema.h
test/include/util/tpcc/util.h

We noticed that `tpcc_test` was taking longer than it used to (2-3x), but throughput on the benchmark hasn't suffered so I suspected the loader. Quickly tracked it down to deep copies of `Schema::Column` and `IndexSchema::Column` objects in `tpcc/util.h` introduced with #481 when writing tuple and index key attributes. These aren't used in the workload because we cache all of the column offsets as if it were compiled code.
- Changed `Schema::GetColumn()` methods to return `const &` to avoid deep copies where possible.
- Changed `tpcc/util.h`'s call to `IndexSchema::GetColumns()` to be used as a `const auto &` to avoid deep copies. The perils of `auto`...

Be smarter about Column copies

---

.travis.yml
CMakeLists.txt
Jenkinsfile

Also rename the different configurations to be consistent. Remove ASAN related stuff from Travis since all we do is static analysis and building, not execute (except for Coverage where we run ASAN off).
I'll watch the build times tonight to see if this completely wrecks our CI time.

Add clang-8 builds to Linux CI

---

Jenkinsfile
script/installation/packages.sh

Adds a timeout mechanism for `make unittest` and `make runbenchmark` for Jenkins.  Motivated by a current bug in one PR that started causing resource starvation of our macOS build machines.
Uses a 1 hour timeout as a conservative baseline (double worst observed successful run).

Add 'timeout' for Ubuntu and 'gtimeout' for macOS

---

CMakeLists.txt

CMAKE_CXX_STANDARD 17 doesn't exist in [3.2](https://cmake.org/cmake/help/v3.2/prop_tgt/CXX_STANDARD.html#prop_tgt:CXX_STANDARD), exists starting with [3.8](https://cmake.org/cmake/help/v3.8/prop_tgt/CXX_STANDARD.html#prop_tgt:CXX_STANDARD).

Bump CMake minimum version from 3.2 to 3.8

---

src/include/storage/tuple_access_strategy.h

There are a couple of leftover functions that are not used any more in tuple access strategy. (They are also no longer correct, but again, not used)

Remove dead code

---

.travis.yml
Jenkinsfile
script/installation/packages.sh

The `llvm` Homebrew package now defaults to 9. We don't want that yet (all the clang-tools and LLVM are untested with the repo right now), so we need to specify 8.

Update LLVM_DIR path for llvm@8 Homebrew package

---

Jenkinsfile

This should reduce the archived size of builds.

Add `make clean` as final step of Jenkins builds

---

src/optimizer/physical_operators.cpp
src/planner/plannodes/drop_trigger_plan_node.cpp
src/planner/plannodes/update_plan_node.cpp

We were hashing the pointers of fields in a couple of the plan nodes. That's not good. We want to hash the actual values.
Somehow this didn't break on our existing toolchain (maybe the stack addresses ended up exactly the same for the fields on back-to-back calls to `Hash()`) but this week's AppleClang release caused a failure. Go figure.

Fix hashing DropTriggerPlanNode and UpdatePlanNode

---

.travis.yml
Jenkinsfile

Homebrew changed the path of the `llvm@8` package, so we need to update our CI to reflect that.

Update LLVM_DIR for macOS

---

src/include/network/network_defs.h
src/include/network/protocol_interpreter.h
test/network/network_test.cpp

Found a bug while refactoring some shared_ptrs in the network layer, turns out this was causing headaches for @GustavoAngulo's replication stuff.
I'm not thrilled with the test, but without the fix it at least trips the two asserts that I added.

Fix InputPacket::Clear() to reset extended_ flag

---

src/include/network/connection_handle.h
src/include/network/itp/itp_command_factory.h
src/include/network/itp/itp_network_commands.h
src/include/network/itp/itp_packet_writer.h
src/include/network/itp/itp_protocol_interpreter.h
src/include/network/network_command.h
src/include/network/network_defs.h
src/include/network/network_io_utils.h
src/include/network/network_io_wrapper.h
src/include/network/packet_writer.h
src/include/network/postgres/postgres_command_factory.h
src/include/network/postgres/postgres_network_commands.h
src/include/network/postgres/postgres_packet_writer.h
src/include/network/postgres/postgres_protocol_interpreter.h
src/include/network/protocol_interpreter.h
src/network/connection_handle.cpp
src/network/itp/itp_command_factory.cpp
src/network/itp/itp_protocol_interpreter.cpp
src/network/network_io_wrapper.cpp
src/network/postgres/postgres_command_factory.cpp
src/network/postgres/postgres_protocol_interpreter.cpp
src/network/postgres/postgres_protocol_utils.cpp
test/network/network_test.cpp

Needed for #401. This clears up the ownership in the network layer.
I still want to make a pass adding some comments now that I understand the behavior a bit better,  but I can at least see how it does in CI.

Remove shared_ptr from the network layer

---

cmake_modules/SetupCxxFlags.cmake

It accidentally got messed up today and we lost some compiler flags on Apple.
Noticed it now while playing around with `-ftime-trace`.

Fix CMake goof on macOS

---

script/installation/packages.sh

Not convinced this dependency is even used right now, but this should fix macOS builds breaking in CI after https://github.com/Homebrew/homebrew-core/pull/46876

Update openssl Homebrew package to 1.1 for macOS

---

script/installation/packages.sh
test/metrics/metrics_test.cpp

I'll try to come up with stricter tests that don't rely on timing, but in the meantime this will help with the CI failures.

Relax metrics_test strictness due to timing issues in CI

---

script/installation/packages.sh
src/catalog/database_catalog.cpp
src/include/catalog/database_catalog.h
src/include/storage/recovery/recovery_manager.h
src/transaction/transaction_manager.cpp
test/catalog/catalog_test.cpp
test/test_util/tpcc/builder.cpp

This is a quick way to avoid write skew anomalies in the catalog when we have concurrent DDL changes that won't trigger write-write conflicts in the storage layer. Any transactions attempting to perform DDL changes must first acquire the database-level lock.
Long term this could be handled with more robust solutions like precision locking (see HyPer paper) but this will save us for now. In the meantime, any DDL change implementations added to the catalog should make sure to honor these semantics and acquire the lock first.
This will allow me to implement DROP SCHEMA (namespace) without worrying about another transaction adding objects to that namespace at the same time.

DDL lock in DatabaseCatalog

---

benchmark/storage/tuple_access_strategy_benchmark.cpp
src/catalog/database_catalog.cpp
src/execution/vm/bytecode_emitter.cpp
src/include/execution/sql/concise_hash_table.h
src/include/storage/index/generic_key.h
src/storage/block_compactor.cpp
test/execution/projected_columns_iterator_test.cpp
test/optimizer/logical_operator_test.cpp
test/storage/index_key_test.cpp
third_party/madoka/sketch.cc

This changeset allows for compilation under GCC9 with LLVM 9 libraries. 
This is not-for-merge for a variety of reasons, including but not limited to:
1. ~~The Wclass-memaccess workaround is a bit cludgy (though, interestingly, RocksDB did the same thing I'm doing here when they switched to GCC9)~~ Still somewhat cludgy, but I think that adding comments has resolved most of the issue here.
2. I'm not convinced there's any interest in a PR regarding toolchain updates at the moment
3. Code review is of course still needed.
The specific changes that have been made are: 
1. Fixing a misleading part of the build configuration that mandates that the LLVM version be exactly 8.0 (and not greater), while stating that it wants an LLVM version greater than *or equal to* 8. This can be made into its …

 More GCC 8+ fixes

---

src/catalog/database_catalog.cpp
src/include/catalog/database_catalog.h
test/catalog/catalog_test.cpp

- `DatabaseCatalog::DeleteTable()` now drops any indexes on the table being dropped. Documentation already said it did this, so no change there.
- `DatabaseCatalog::DeleteNamespace()` now drops any tables and indexes on the namespace being dropped. Documentation already said it did this, so no change there.
- Added a couple of internal functions to make it easier, though these could be exposed via `CatalogAccessor` if desired in the future.
- Test cases.

Cascading DROP logic for table and namespace

---

src/binder/bind_node_visitor.cpp
src/binder/binder_context.cpp
src/catalog/catalog_accessor.cpp
src/include/binder/binder_context.h
src/include/parser/expression/column_value_expression.h
src/include/parser/sql_statement.h
src/include/parser/table_ref.h
src/parser/postgresparser.cpp
test/parser/expression_test.cpp
test/parser/parser_test.cpp

This PR does the following:
1. Look up table OID based on namespace (return DEFAULT NAMESPACE if namespace name is unspecified), this will allow prepared statements to be resolved in similar ways
2. Rename SchemaName -> Namespace Name in TableRef
3. Remove unused field "namespace_name_" in ColumnValueExpression

Binder namespace binding refactor

---

benchmark/parser/parser_benchmark.cpp
src/include/parser/postgresparser.h
src/include/planner/plannodes/index_scan_plan_node.h
src/parser/postgresparser.cpp
test/binder/binder_test.cpp
test/optimizer/operator_transformer_test.cpp
test/parser/expression_test.cpp
test/parser/parser_test.cpp
test/test_util/tpcc/tpcc_plan_test.cpp

All of the internal methods are already `static`, only non-`static` method is the single public API function. There's no state stored, so just made the entire class `static`.
This came up while trying to reason about object ownership of `PostgresParser` when I noticed that there's really no point in instantiating an object to be owned.

Static PostgresParser

---

.travis.yml

Trying to fix what I believe to be a recent change to the Travis macOS image which manifests as:
```
==> Installing tbb dependency: python
896==> Downloading https://homebrew.bintray.com/bottles/python-3.7.6_1.mojave.bottl
897==> Downloading from https://akamai.bintray.com/64/643d627c2b4fc03a3286c397d2992
898######################################################################## 100.0%
899==> Pouring python-3.7.6_1.mojave.bottle.tar.gz
900Error: The `brew link` step did not complete successfully
901The formula built, but is not symlinked into /usr/local
902Could not symlink Frameworks/Python.framework/Headers
903Target /usr/local/Frameworks/Python.framework/Headers
904is a symlink belonging to python@2. You can unlink it:
905  brew unlink python@2
906
907To force the link and overwrite …
```

Travis: Unlink Homebrew's python@2 formula before running packages.sh

---

src/execution/compiler/codegen.cpp

Pass the `std::string_view`'s length to the constructor of the `LLVM::StringRef` since otherwise LLVM tries to do`strlen` which breaks because they're not null-terminated.
I ran `compiler_test` locally and it looks fine, and will merge after it finishes CI.
Fixes a segfault seen on `INSERT INTO HISTORY VALUES (1,1,1,1,1,1,1.0,'A')` after bootstrapping TPC-C.

Fix CodeGen::StringToSql

---

src/execution/compiler/operator/insert_translator.cpp
src/execution/compiler/operator/update_translator.cpp
src/execution/sema/sema_builtin.cpp
src/execution/sql/storage_interface.cpp
src/execution/vm/bytecode_generator.cpp
src/execution/vm/bytecode_handlers.cpp
src/execution/vm/vm.cpp
src/include/execution/ast/builtins.h
src/include/execution/sql/storage_interface.h
src/include/execution/vm/bytecode_handlers.h
src/include/execution/vm/bytecodes.h

`InsertTranslator` and `UpdateTranslator` only generate the non-unique insert method for the index wrapper, resulting in a failed assertion with a unique index. Hooray for the storage layer keeping us honest.
Fixes a failure seen on `INSERT INTO \"NEW ORDER\" VALUES (1,2,3)` after bootstrapping TPC-C.

Add Index::InsertUnique logic to CodeGen

---

src/catalog/catalog.cpp
src/catalog/catalog_accessor.cpp
src/include/catalog/catalog.h
src/include/catalog/catalog_accessor.h

The plan node for `CREATE TABLE` needs a pointer to a `BlockStore` in order to be executed. We decided that this should come from the `CatalogAccessor`. In order to facilitate as quickly as possible, this just returns the `BlockStore` that was passed to the `Catalog` as a dependency to be used for its tables. Open questions remain, and will not be addressed in this PR:
1. What is the scope of a `BlockStore`. System-wide? Per-database?
2. Does it belong in a proper table a la `pg_tablespace`?
3. Does `BlockStore` usage even make sense, or should we just be relying on jemalloc to allocate new `RawBlock`s for us? I am not convinced of `BlockStore`'s benefits right now.

Add GetBlockStore() to Catalog and CatalogAccessor.

---

src/include/main/db_main.h
src/storage/write_ahead_log/disk_log_consumer_task.cpp
src/storage/write_ahead_log/log_serializer_task.cpp
test/storage/log_test.cpp

Issue: Nothing gets serialized into a buffer for read-only txns, but the condition for handing stuff to the disk consumer task (responsible for invoking commit callbacks) is if anything was serialized. 
How to reproduce: send `BEGIN; COMMIT;` over psql and seeing `COMMIT;` block forever.
Changes:
- `LogSerializerTask` will hand off what it has to `DiskLogConsumerTask` if it processed any log records, regardless of whether it serialized anything from those records
- `DiskLogConsumerTask` checks in case it's processing an empty buffer (all read-only txns) rather than blindly dereferencing it (which was safe and protected by an assertion before).
- Added a test with a real callback to verify correctness.
- Fixed an unrelated bug in `DBMain` for one of the args to the `LogManager`.

Fix read-only txns commit callback not invoked with logging enabled

---

src/execution/compiler/operator/index_scan_translator.cpp
src/execution/compiler/operator/seq_scan_translator.cpp
src/include/optimizer/plan_generator.h
src/include/planner/plannodes/index_scan_plan_node.h
src/include/planner/plannodes/seq_scan_plan_node.h
src/optimizer/plan_generator.cpp
test/execution/compiler_test.cpp
test/optimizer/tpcc_plan_delivery_test.cpp
test/optimizer/tpcc_plan_index_scan.cpp
test/optimizer/tpcc_plan_neworder_test.cpp
test/optimizer/tpcc_plan_payment_test.cpp
test/optimizer/tpcc_plan_seq_scan.cpp

PR fixes the following set of bugs between the optimizer and execution engine:
(actual index scans will be fixed in a separate PR)

OutputSchema and assorted PlanGenerator fixes

---

src/parser/postgresparser.cpp

Found with `CREATE TABLE test.foo (id INTEGER);`. If you specified a database name as well it probably would have worked.

Fix segfault in PostgresParser from creating table in a namespace

---

src/execution/executable_query.cpp

This will help us figure out codegen issues faster without having to recompile with the debug logger for execution level changed.

Dump the AST when an error occurs in code compilation.

---

src/main/terrier.cpp

@apavlo wants stronger wording around that global `db_main_ptr` so I did that, and switched it to anonymous namespace instead of older C-style `static` declaration for internal linkage.

Stronger comments and favor anonymous namespace for db_main_handler_ptr

---

src/binder/binder_context.cpp

Fix #707.
pg_catalog not ending up in the default namespace search path
The issue was when running the query
terrier=# select * from pg_index;
ERROR:  binding failed
We shouldn't have to qualify pg_catalog.pg_index. It was in the binder context's AddRegularTable method when passing the empty string for the namespace. It set it to default, public. Then uses this public namespace and the table name (even though the table is not in public) to fetch the tableoid, where it was getting the binding issue.
Tested it out locally on
select * from pg_index;
select * from pg_class;

pg_catalog not ending up in the default namespace search path

---

src/optimizer/query_to_operator_transformer.cpp

Fix #706.
```
terrier=# create schema foo;
CREATE SCHEMA
terrier=# create table foo.bar (id integer);
CREATE TABLE
terrier=# SELECT * from pg_catalog.pg_class;
```
The results show that the table ends up in the public namespace rather than foo, so there's a bug somewhere. 
This PR: default namespace was being used and thats why the table was always created under the public namespace.

CREATE TABLE with a qualified namespace work as expected

---

src/include/optimizer/physical_operators.h
src/optimizer/child_property_deriver.cpp
src/optimizer/physical_operators.cpp
src/optimizer/plan_generator.cpp
src/optimizer/rules/implementation_rules.cpp
test/optimizer/physical_operator_test.cpp

Prior to this commit, performing a query like `SELECT * from foo f where f.id = 1` that utilizes an index scan would trigger an assertion failure in the catalog. This PR replaces the table alias stored within the `IndexScan` with the actual table's oid.

IndexScan Table Alias Fix

---

src/main/db_main.cpp
src/network/terrier_server.cpp

System now properly handles failing to bind to a socket already in use:
```
[2020-02-03 15:07:45.951] [network_logger] [error] Failed to bind socket: Address already in use
```
Fix #732.

TerrierServer throws on socket already in use, DBMain catches and returns

---

src/include/network/connection_handler_task.h
src/network/connection_handler_task.cpp
test/network/network_test.cpp

Aims to close issue #413 where more connections than CONNECTION_THREAD_COUNT would overwrite an existing ConnectionHandlerTasks client_fd_ and protocol_handler_ fields before it is able to create a valid ConnectionHandle and start it. The fix was turning these fields into queues that are protected by a SpinLatch. The contention is expected to be low on this.

Race Condition Fix in ConnectionHandlerTask

---

script/installation/packages.sh

Somebody in the class tried to install the system on Amazon's distro of Linux. Right now packages.sh only checks whether you are running Linux and not which distribution. This PR adds for checking that you are trying to install on Ubuntu. I tested on CentOS and the output format of the error report is correct.
This also adds support for Ubuntu 19.04/19.10, which we may not want to do right now.
https://youtu.be/an9Qqf9dxG4

Improved distribution checking in packages.sh

---

Jenkinsfile

On Jenkins, we build the project and then immediately delete the build. We then go directly onto the next stage where we build it again.
Deleting this shaves >20 minutes off of CI builds.

Remove unnecessary make in Jenkins' "Check" stage

---

Dockerfile
script/installation/packages.sh
test/network/network_test.cpp

This upgrades libpqxx to v6.2.4-5 and disables `NetworkTest::RacerTest`.
https://youtu.be/-wPYskRn7MM

Upgraded libpqxx + Disable NetworkTest::RacerTest

---

script/testing/junit/src/UpdateTest.java
src/binder/bind_node_visitor.cpp
test/optimizer/tpcc_plan_delivery_test.cpp
test/optimizer/tpcc_plan_neworder_test.cpp
test/optimizer/tpcc_plan_payment_test.cpp

Fix #783, includes a JUnit test.
This also fixes bad types in old tests, e.g. in the optimizer/tpcc_ family of tests, there were cases where the transient value returned was of the wrong type (such as INTEGER instead of SMALLINT).
Just more binder hacks..

Binder logic to convert mismatched types in update statements.

---

script/testing/junit/src/SelectTest.java
src/optimizer/rules/implementation_rules.cpp
src/parser/postgresparser.cpp

Fix for #793 
Test:
```
terrier=# CREATE TABLE xxx (id INT);
CREATE TABLE
terrier=# INSERT INTO xxx VALUES (1),(2),(3),(4);
INSERT 0 4
terrier=# SELECT COUNT(*) AS cnt FROM xxx HAVING COUNT(*) > 10;
cnt 
-----
(0 rows)
```

 Fix Having Clause (#793)

---

test/storage/bwtree_index_test.cpp

I don't think we've seen this error on master, which is odd. Regardless, a student pointed out that we're clearing the results vector in the test and then reading an element from it. I moved the `results.clear()` calls down to when it should be safe.

bwtree_index_test: fix potential bad access in results vector

---

Jenkinsfile
script/jenkins/benchmark-agent-setup.sh
script/jenkins/docker-agent-setup.sh

@portablesounds pinged me recently about using ccache in the CI environment.  This PR does that.
Here's a sample of the time savings for a single stage, `-DCMAKE_BUILD_TYPE=Debug -DTERRIER_USE_ASAN=ON && time make -j$(nproc)`:
First run:
```
...
[100%] Built target recovery_benchmark
real    7m11.187s
user    116m16.729s
sys     10m35.875s
```
Second run in a new container on the same Docker host:
```
...
[100%] Built target tpch_runner
real    1m56.294s
user    26m8.217s
sys     4m22.803s
```
Running on the full pipeline saved 30 minutes (comparing branches master to ccache):
http://jenkins.db.cs.cmu.edu:8080/job/crd/job/terrier-crd/
It should get a little better as more things wind up in the cache but I was surprised how much of the total time is consumed by the tests; ccache won't help …

Enable ccache in Jenkins

---

src/include/main/db_main.h
src/include/network/network_defs.h
src/include/network/terrier_server.h
src/include/settings/settings_defs.h
src/network/terrier_server.cpp
test/network/network_test.cpp

`connection_thread_count` will now change the default number of client connection thread handlers to whatever the command line argument value is. Default is still 4.
For future reference, the model of changing something to a setting: add to `settings_defs.h`, read the value back out where needed, and added it as a member to `DBMain` since it needs a default value to use whenever the `SettingsManager` is not being used.

Change connection thread count to be a setting instead of a `#define`

---

src/execution/executable_query.cpp
src/include/execution/executable_query.h
src/include/main/db_main.h
src/include/network/postgres/portal.h
src/include/network/postgres/postgres_protocol_interpreter.h
src/include/network/postgres/statement.h
src/include/settings/settings_defs.h
src/include/traffic_cop/traffic_cop.h
src/network/postgres/postgres_network_commands.cpp
src/traffic_cop/traffic_cop.cpp
test/network/network_test.cpp

At a high level, this implements a mechanism to cache physical plans and `ExecutableQuery` (TPL module, AST context, etc.) from code generation in `PostgresProtocolInterpreter`. It relies on libpgquery's pg_fingerprint functionality to identify statements. It builds on top of the Postgres extended query protocol, and doesn't change anything for simple query.
Changes:
- `ExecutableQuery` stashes the main function as a member.
- `Portal` no longer owns the physical plan, but holds a `ManagedPointer` to it.
- `Statement` owns the physical plan and `ExecutableQuery` of its bound `Portal`s. A `Portal` just describes the parameters and output format for that invocation of the `Statement`.
- A new map in `PostgresProtocolInterpreter` from fingerprint to owned `Statement`. The old `Statement` map …

Compiled query caching added to PostgresProtocolInterpreter

---

test/traffic_cop/traffic_cop_test.cpp

libpqxx got rid of the explicit `disconnect()` method, however connections are closed on destruction in both 6.x and 7.x so this change should be fine regardless of library version. This is necessary because Homebrew is now pushing 7.x and the `libpqxx@6` target can be installed, but is deprecated.
There's a longer discussion to be had at some point of if we still want it at all.

Update traffic_cop_test for libpqxx 7.x

---

src/include/execution/vm/bytecode_handlers.h

Introduced by #911. Caught this while trying to run TPC-C in Extended Query mode locally. Should use Content() to access StringVal, not assume it's the inlined pointer.

Fix bug in OpGetParamString in bytecode_handlers

---

script/testing/junit/src/TrafficCopTest.java
src/network/postgres/postgres_protocol_interpreter.cpp

If the client disconnects and there is an open txn, abort it. Otherwise the system could end up in a bad state where that txn is never GC'd and version chains never get cleaned up.
**Major changes:**
- Extended `Teardown` logic in `PostgresProtocolInterpreter` to abort any running txn belonging to its `ConnectionContext`.
- JUnit test case that fails on current master to show the issue is fixed

Abort running txn on disconnect

---

script/testing/junit/src/TrafficCopTest.java

Trying to reduce spurious failures. Introduce a sleep to DisconnectAbort to try to get the abort to fully process before firing off any more queries that are supposed to succeed. I'm thinking the server might not be done with all of the abort logic when the next query fires off which can cause a write-write conflict when we don't expect one anymore.

Add a small sleep to DisconnectAbort JUnit test

---

Jenkinsfile-nightly

The [nightly builds](http://jenkins.db.cs.cmu.edu:8080/blue/organizations/jenkins/terrier-nightly/detail/terrier-nightly/10/pipeline/) skipped Performance and Microbenchmark stages. Because the `branch` condition only works on a multibranch Pipeline. We configured the branch as `*/master` on the webpage so we don't need it in the Jenkinsfile

Fix nightly build timer

---

src/include/storage/index/bwtree_index.h
src/include/storage/index/hash_index.h
src/include/storage/index/index.h
src/storage/block_compactor.cpp
src/storage/index/bwtree_index.cpp
src/storage/index/hash_index.cpp
src/storage/recovery/recovery_manager.cpp
third_party/bwtree/bwtree.h

This gets the third party bwtree.h and cuckoohash_map.hh headers out of our header files and not getting parsed and clang-tidy'd again all over the codebase,

Move index wrapper definitions to cpp files

---

src/include/execution/util/simd/avx512.h

Fix for AVX512 on macOS, since now Mac support AVX512

Fix for AVX512 on macOS

---

src/include/optimizer/cost_model/trivial_cost_model.h
src/include/optimizer/input_column_deriver.h
src/include/optimizer/logical_operators.h
src/include/optimizer/operator_visitor.h
src/include/optimizer/optimizer_context.h
src/include/optimizer/physical_operators.h
src/include/optimizer/plan_generator.h
src/optimizer/binding.cpp
src/optimizer/child_property_deriver.cpp
src/optimizer/cost_model/trivial_cost_model.cpp
src/optimizer/optimizer_context.cpp
src/optimizer/plan_generator.cpp
src/optimizer/rules/implementation_rules.cpp
src/optimizer/rules/rewrite_rules.cpp
src/optimizer/rules/transformation_rules.cpp
src/optimizer/rules/unnesting_rules.cpp
src/optimizer/statistics/child_stats_deriver.cpp
src/optimizer/statistics/stats_calculator.cpp
test/optimizer/operator_transformer_test.cpp
test/optimizer/optimizer_context_test.cpp

logical_operators.h and physical_operators.h are both over 2000 lines, included in operator_visitor.h, which in turn is included in a bunch of other headers so it propagates. This PR makes it so only the translation units that need them include those files.

Clean up optimizer includes a bit

---

src/include/main/db_main.h
src/include/settings/settings_callbacks.h
src/include/settings/settings_defs.h
src/settings/settings_callbacks.cpp
test/metrics/metrics_test.cpp

We have settings to toggle per-component metrics at runtime, but I never hooked them up to DBMain's builder to enable them if they were turned on at the command line at server launch. This fixes that problem.

Hook up per-component metrics settings to DBMain's Builder

---

src/include/loggers/metrics_logger.h
src/include/metrics/metrics_store.h
src/loggers/loggers_util.cpp
src/loggers/metrics_logger.cpp
src/storage/write_ahead_log/disk_log_consumer_task.cpp
src/storage/write_ahead_log/log_serializer_task.cpp
src/transaction/transaction_manager.cpp

There's a race condition between disabling a component's metrics and the component potentially still wanting to record one of its data points. We had asserts that would trip occasionally in this event (see [this recent Jenkins run](http://jenkins.db.cs.cmu.edu:8080/blue/organizations/jenkins/terrier/detail/master/593/tests/)). This relaxes the assert to just use the (new) `MetricsLogger` to print out a warning message.

Relax asserts in MetricsStore

---

src/execution/util/cpu_info.cpp

Doing a quick trial on AMD Epyc, I encountered a bug in `InitCpuInfo()`.  It currently relies on regex matching "GHz" in `/proc/cpuinfo` to set the base frequency and works correctly on model names like:
```model name      : Intel(R) Xeon(R) CPU E5-2620 v3 @ 2.40GHz```
On AMD Epyc, no clock speed is presented:
```model name      : AMD EPYC 7452 32-Core Processor```
This results in `stod()` being called on an empty `cmatch` and causing crashes like the following:
```
crd@epyc:/mnt/terrier/build$ gdb ./debug/terrier
GNU gdb (Ubuntu 8.1-0ubuntu3.2) 8.1.0.20180409-git
Copyright (C) 2018 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the …
```

ensure the match is not empty before assigning ref_cycles_us_

---

src/include/loggers/loggers_util.h
src/include/network/terrier_server.h
src/include/optimizer/binding.h
src/include/storage/write_ahead_log/disk_log_consumer_task.h
src/include/storage/write_ahead_log/log_serializer_task.h
src/loggers/binder_logger.cpp
src/loggers/catalog_logger.cpp
src/loggers/common_logger.cpp
src/loggers/execution_logger.cpp
src/loggers/index_logger.cpp
src/loggers/loggers_util.cpp
src/loggers/metrics_logger.cpp
src/loggers/network_logger.cpp
src/loggers/optimizer_logger.cpp
src/loggers/parser_logger.cpp
src/loggers/settings_logger.cpp
src/loggers/storage_logger.cpp
src/loggers/transaction_logger.cpp
src/optimizer/binding.cpp
src/optimizer/group.cpp
src/optimizer/optimizer.cpp
src/optimizer/optimizer_task.cpp
test/network/network_test.cpp
test/optimizer/top_k_elements_test.cpp
test/parser/parser_test.cpp

Mostly for @abalakumar083 to run his compilation time analysis on. If it seems to actually trim down the time spent in template instantiation, we may merge it. The win wasn't huge for me locally:
**Master:**
```
make -j12  2376.07s user 143.76s system 1019% cpu 4:07.27 total
```
**This PR:**
```
make -j12  2285.42s user 135.46s system 1026% cpu 3:55.78 total
```

Explicit instantiation of spdlog template functions

---

script/testing/junit/src/SelectTest.java
src/execution/sema/sema_expr.cpp
src/execution/vm/bytecode_generator.cpp
src/execution/vm/vm.cpp
src/include/execution/ast/type.h
src/include/execution/sql/functions/comparison_functions.h
src/include/execution/vm/bytecode_handlers.h
src/include/execution/vm/bytecodes.h

The NOT expression did not work in terrier, because the operator only accepted primitive booleans. These changes overload the NOT operator to also accept SQL booleans, which fixes the issue.

Adding support for NOT expression

---

script/testing/oltpbench/test_oltpbench.py

The nightly Jenkins job [failed](http://jenkins.db.cs.cmu.edu:8080/blue/organizations/jenkins/terrier-nightly/detail/terrier-nightly/29/pipeline) because there is a conflict in oltpbench results folders. For each different testing, oltpbench needs different folders to put testing results.

fix oltpbench results folder conficts

---

test/storage/export_table_test.cpp

Issue #1013 raised two action items of export_table_test:
- Increase debugability;
- Fix potential bugs that caused random failures.
The first one was solved by:
1. Moving assertions into `CheckContent` so that we can distinguish different failure cases; 
2. Providing the location of mismatch data, i.e., which row and column has unexpected data; 
3. Reserving the seed and exported file if there are failures so that the failure can be reproduced.
The second item was solved by identifying a rare case where when a row only contains a single null value, it was exported as `""\n`. `\n` is its only delimiter but was not properly parsed before, so when such row was generated, the test would fail.
The new version of the test in this RB has been verified by repeating 3000 times without failures.

Issue #1013: Fix Random Failure Bugs & Add More Debug Info

---

Jenkinsfile
script/testing/junit/build.xml
script/testing/junit/constants.py
script/testing/junit/run_junit.py
script/testing/junit/src/TracefileTest.java
script/testing/junit/test_junit.py
script/testing/util/constants.py
src/include/main/db_main.h
src/include/network/connection_handle.h
test/network/network_test.cpp

This PR is focused on fixing up the junit tracefile testing code. I am going to rename the files in [noisepage-testfiles](https://github.com/cmu-db/noisepage-testfiles), but I want to make sure that this works first.
* Cleaned up tracefile testing Python code
* Moved Postgres-specific code out of ConnectionHandle
* Simplify Jenkinsfile and make sure we only build the server binary for end-to-end tests
When the build passes, I will rename the files in the separate repo and then push a commit.
https://youtu.be/GMMpzTw7WDA

JUnit Trace File Testing Fixes/Cleanup

---

script/micro_bench/run_micro_bench.py

We moved the testing team's new nightly job on Jenkins to replace the old 'terrier-nightly'. This reset the build number. This caused a problem in the microbenchmark script because Pervaze had set it to ignore any data **before** 363. I also had to modify the code to ignore any artifact file that is not from the microbenchmarks (e.g., OLTP-Bench files). This fixes #1033.
https://youtu.be/FfIj2VOfg8s

Re-enable Microbenchmark Regression Checks

---

src/include/main/db_main.h
src/include/settings/settings_defs.h
src/include/traffic_cop/traffic_cop.h
src/traffic_cop/traffic_cop.cpp
test/network/network_test.cpp

Add `compiled_query_execution` boolean arg to enable LLVM compilation instead of TPL interpretation. Default is to interpret. Currently doesn't allow for enabling adaptive mode since that doesn't work anyway on short queries due to object life cycle issues.

compiled_query_execution command line arg

---

script/micro_bench/run_micro_bench.py

Suggested by @apavlo. The microbenchmarks are noisy and we end up merging a lot of stuff that fails that stage. Does anyone have objections?

Increase microbenchmark lax_tolerance from 30 to 50.

---

test/execution/sql_filter_manager_test.cpp

Noise is apparently massive in some situations, which can cause spurious test failures. As a result, we disable this test on Apple machines and get false positives on others. However, steps can be taken to decrease the noise and increase the signal for this test, such that false positives are exceedingly unlikely.
To do so, this commit increases the average number of samples taken and dramatically increasing the overhead of the "slow" filters, respectively. For added effect, we exaggerate selectivity differences as well. This is mostly apparent in execution traces.
This _should_ (we have to wait for Jenkins results) fix the test failures noted by Wan, which would allow this test to be ran on Apple machines. It would also fix some spurious test failures that I've encountered.

Fix AdaptiveCheckTest in sql_filter_manager_test.cpp

---

benchmark/runner/mini_runners.cpp
test/execution/parsing_scanner_test.cpp
test/execution/sql_sorter_test.cpp
test/execution/sql_thread_state_container_test.cpp
test/execution/util_chunked_vector_test.cpp

Ran check-clang-tidy with the flag to apply fixes in the background while working on other stuff. Diff looks reasonable.
Fix #1119.

Address check-clang-tidy issues on master

---

script/testing/junit/traces/create_index.test
src/execution/compiler/operator/index_create_translator.cpp

Since there isn't a corresponding issue, the bug (with repro) is as follows:
From this commit: efcb7e6311c784500cba3b9baa8d2c9fdf11f503
```
psql (10.14 (Ubuntu 10.14-0ubuntu0.18.04.1), server 9.5devel)
Type "help" for help.
terrier=# create table t (a INT, b INT, c INT);
CREATE TABLE
terrier=# insert into t values (1, 2, 3);
INSERT 0 1
terrier=# create index idx on t (c);
CREATE INDEX
terrier=# select * from t where c = 3;
a | b | c 
---+---+---
(0 rows)
terrier=# create index idx_a on t (a);
CREATE INDEX
terrier=# select * from t where a = 1;
a | b | c 
---+---+---
1 | 2 | 3
(1 row)
terrier=# select * from t where c = 3;
a | b | c 
---+---+---
(0 rows)
```
The fix corrects the offset passed to `VPIGet` when fetching a column value that is needed when constructing the PR in preparation …

Fix CREATE INDEX creation of PR

---

src/execution/compiler/executable_query.cpp
src/execution/compiler/operator/csv_scan_translator.cpp
src/execution/compiler/operator/operator_translator.cpp
src/execution/compiler/operator/seq_scan_translator.cpp
src/execution/sql/sql.cpp
src/execution/sql/vector_operations/arithmetic.cpp
src/execution/sql/vector_operations/fill.cpp
src/execution/sql/vector_operations/gather.cpp
src/execution/sql/vector_operations/gather_select.cpp
src/execution/sql/vector_operations/generate.cpp
src/execution/sql/vector_operations/hash.cpp
src/execution/sql/vector_operations/inplace_arithmetic.cpp
src/execution/sql/vector_operations/inplace_bitwise.cpp
src/execution/sql/vector_operations/like.cpp
src/execution/sql/vector_operations/select.cpp
src/include/common/error/exception.h
src/include/execution/sql/operators/cast_operators.h
src/include/execution/sql/vector_operations/inplace_operation_executor.h
src/traffic_cop/traffic_cop.cpp

Currently there are various places where ExecutionException can be
thrown from, mostly only reachable through software bugs. Before
this commit they will be fatal and cause the DB to crash.
This commit now handles ExecutionExceptions byt causing the
transaction to abort, and returning an error message to the user.

Handle Execution Exceptions

---

third_party/xxHash/xxh3.h
third_party/xxHash/xxhash.c
third_party/xxHash/xxhash.h

It's much smaller. This helps a lot with build times. (~10-15% faster for me.) There ought to be some low-hanging fruit that would make it possible to shrink xxhash even more, but I'll revisit this PR tomorrow.
This was inspired by #1074. Wan gave me the go-ahead to make this a separate PR. Hoping that this could be useful with the issue that #1074 faces.

Shrink xxHash include

---

src/include/execution/vm/bytecode_handlers.h

Add missing EXPORT to bytecode handler.
Fixes TPCH Q4, Q16, Q19 in compiled mode - it was segfaulting because nothing got compiled, and that was because symbols were missing.
Also, don't forget to build the `tpl` target so that `bytecode_handlers_ir.bc` is generated. You may need to regenerate that file every time you switch branches that mess with bytecodes.
Let me know if this works for you? @malin1993ml Thanks!

Add EXPORT to bytecode handler to fix TPCH runner compiled mode.

---

benchmark/storage/varlen_entry_benchmark.cpp
script/micro_bench/run_micro_bench.py
src/include/common/hash_util.h
src/include/storage/storage_defs.h

It's just too noisy to be reliable. Added documentation that performance should be looked at critically using the benchmark locally if exercised code is changed.

Remove varlen_entry_benchmark from CI

---

src/include/storage/write_ahead_log/log_io.h

[fdatasync](https://linux.die.net/man/2/fdatasync) is used as an optimization on Linux since we don't care about all of the file's metadata being persisted, just the contents. macOS does not provide this syscall.

Prefer fdatasync over fsync of WAL on supported platforms

---

src/binder/binder_util.cpp
src/catalog/database_catalog.cpp
src/include/common/container/concurrent_bitmap.h
src/include/execution/exec/execution_context.h
src/include/execution/exec/output.h
src/include/execution/sql/operators/cast_operators.h
src/include/storage/access_observer.h
src/traffic_cop/traffic_cop.cpp
third_party/nlohmann/detail/output/serializer.hpp
third_party/spdlog/common.h

This collection of fixes allows us to build using clang-10 and gcc-10.
Note that this does not allow us to build using llvm-10's libraries. This is purely addressing the new warnings. In the process, though, it does make some functional changes: 
1. RowsAffected and NumRows now return a uint32_t. Technically speaking, this limits the number of rows we can return to ~4 billion. Practically speaking, we were always limited to ~4 billion because the network protocol is uses uint32_ts to tell the client how many rows it's returning. 
This just propagates the fundamental network limits through the type system. 
(While I'm pretty sure a whole lot of other things will break before TrafficCop if we ever try to return 4 billion rows, this change had to be made in order for us to build under …

Toolchain related fixes

---

Jenkinsfile-nightly
script/testing/oltpbench/reporting/constants.py
script/testing/oltpbench/reporting/parsers/res_parser.py
script/testing/oltpbench/reporting/parsers/summary_parser.py
script/testing/oltpbench/test_case_oltp.py

There is currently a bug in the oltpbench scripts where the latency numbers are converted into ints before being sent to the performance storage service. This causes problems with the Grafana visualizations because a number of the latency metrics end up being <1. This causes /0 errors as you can see here https://stats.noise.page/grafana/d/latency_trends/latency-trends?orgId=1
This PR fixes this issue and refactors the code by implementing reuse to give a single place to control the parsing of latency metric labels. This will be especially helpful if https://github.com/oltpbenchmark/oltpbench/pull/338 gets merged (though it also works without that other PR).
I tested this code on both pipelines:
Terrier: http://jenkins.db.cs.cmu.edu:8080/blue/organizations/jenkins/testing-team%2Fterrier/det …

Latency int bug

---

src/storage/garbage_collector.cpp

There is a very unlikely race between the garbage collector's logic and the compactor's logic that could cause both memory leaks and use-after-free errors.  Note:  This race cannot occur in the current codebase because the compactor is not used.
The GC will do the following:
1. Truncate the version chain
2. Reclaim the tuple slot (i.e. mark it as unallocated)
3. Reclaim varlens (i.e. collect the underlying pointers for a call to free)
Meanwhile the compactor's logic:
1. Iterate over the block recording all slots marked unallocated
2. Select the last slot in the region being compacted and perform a deep copy of all varlens
3. Inserts the materialized tuple into the first available unallocated spot.
If the compactor's logic executes from start to finish in between steps 2 and 3 of the GC's …

Fix GC-Compactor race in storage layer

---

Jenkinsfile
script/installation/packages.sh

- Packages.sh is now checking against 20.04.
- Add `libpqxx-dev` to the Linux package list rather than `wget`ing it.
- Jenkins will use the `terrier:focal` image now.

Ubuntu 20.04 fixes for packages.sh and Jenkinsfile

---

src/include/storage/write_ahead_log/disk_log_consumer_task.h
src/storage/write_ahead_log/disk_log_consumer_task.cpp
src/storage/write_ahead_log/log_manager.cpp
src/storage/write_ahead_log/log_serializer_task.cpp

Probably a merge error somewhere in the 10,000 line diff of #774.
Also renamed a variable to make its purpose more clear. This is part of a more exhaustive review of WAL performance.

WAL: Remove redundant call between serializer and disk consumer

---

Jenkinsfile
build-support/check_github_labels.py

Fail fast when building on Jenkins unless ready-for-review or ready-to-merge labels are present.

Fail fast on Jenkins without "ready" GitHub labels.

---

CMakeLists.txt
Jenkinsfile-nightly

Add explicit dependencies to CMake and -GNinja to nightly Jenkinsfile.
Dependencies added:
- noisepage_objlib (spdlog)
- test_util libs (gtest gtest_main gmock gmock_main)
- benchmark_util libs (gtest gtest_main gmock gmock_main)
Dependencies are built in release because the debug versions have unacceptable performance for coverage builds. Especially spdlog. `make` appears to struggle to figure these dependencies out on its own.
spdlog is not added as a true dependency because the library name changes between debug mode and release mode, namely libspdlogd.a versus libspdlog.a. Due to the different names, the build system gets confused.
Therefore the dependency is manually added.
The nightly Jenkinsfile is an omission I made.

Add explicit dependencies to CMake and -GNinja to nightly.

---

CMakeLists.txt

This fixes symbols not being found despite being marked EXPORT as VM_COLD.
@17zhangw confirmed this works.
Not caught since we don't run benchmarks that use these in CI.

Add ENABLE_EXPORTS ON to benchmark targets.

---

CMakeLists.txt

The dependencies have to be added to an object library because adding the dependencies to a target causes a linking attempt that will fail. The linking fails because the linker is looking for the debug version.

Add all weird CMake dependencies to noisepage_objlib instead of real targets.

---

CMakeLists.txt

_Hopefully_ this makes the mac build happy.

Add CMake dependencies with add_custom_command instead of add_dependencies.

---

CMakeLists.txt

CLion's remote toolchain functionality seems to lose `+x` attributes on files when they're rsync'd to the remote host. This adds a step to the CMake file that ensures the required scripts in `build-support` have `+x`.

CMake: Apply +x to build-support for CLion's remote host compatibility.

---

src/include/execution/sql/memory_tracker.h

Fixes memory tracking in parallel by moving `allocated_bytes_` in the MemoryTracker into `tbb::enumerable_thread_specific`.

Fix Memory Tracking Issue (#1250)

---

script/testing/junit/traces/nested-query.test

Fixes #1266 
The current trace configuration sorts on a non-unique column (`pno`) even though it expects a single canonical ordering.  The `part_name` column is prefixed in such a way that it provides a canonical ordering that matches the expected hash values.

Fixes `nested-query.test` by providing a canonical sort order

---

Jenkinsfile-nightly

This adds catchError statements in the nightly build so that as many steps as possible can execute. This makes sure that we are getting and storing as much data as possible. It also means that if a stage fails the other stages can still execute. Also it will still look like it failed when you look at Jenkins this will make sure that we aren't just ignoring failures when they happen. Here is an example: http://jenkins.db.cs.cmu.edu:8080/blue/organizations/jenkins/testing-team%2Fterrier-nightly/detail/flip-night-stages/2/pipeline/39/

Graceful Failures in Nightly Build

---

CMakeLists.txt

I was testing our compilation time with `make` and realized that `make` doesn't pick up the `DEPENDS` command properly, so you end up with issues trying to link to the nonexistent `spdlog`. Merging this should allow you to do a clean build with `make`. Not caught because I moved CI to `ninja`.

Fix spdlog in CMake.

---

Jenkinsfile
src/messenger/messenger.cpp

clang-tidy is busted with unity builds. To reproduce, grab current master: clang-tidy blows up on messenger with unity builds off, doesn't blow up with unity builds on. I don't understand why because in theory it scans over the same code anyway.
This PR:
- moves clang-tidy to the format stage. This should be good because (1) clang-tidy is deterministic, our tests are not, so this saves us time when restarting Test stage; (2) we have a ready-for-ci tag, so CI won't reach the format stage unless we want it to, so we don't have too much wasted resource consumption there
- fixes clang-tidy stuff that was not caught.
Thanks @jkosh44 for pointing out stuff was busted

Fix clang-tidy.

---

script/testing/junit/traces/update.test
src/binder/bind_node_visitor.cpp

There was a binding error for updates of the form `UPDATE foo SET a=a` because the check for `a`'s type happened before `a` was given a type from the schema.
Comes with a test.
Thanks @17zhangw for pointing out the bug.

Fix UPDATE foo SET a=a in the binder.

---

script/testing/reporting/parsers/parse_data.py

Currently, there is an issue if the microbenchmarks try to report results with more than 15 decimal places. This will round all the microbenchmark results to 15 decimal places which should be way more than enough.
Example of the issue here: http://jenkins.db.cs.cmu.edu:8080/blue/organizations/jenkins/terrier-nightly/detail/terrier-nightly/146/pipeline/39

Hotfix Microbenchmark Decimal Reporting

---

script/testing/junit/sql/update.sql
script/testing/junit/src/GenerateTrace.java
script/testing/junit/traces/update.test

Fixes #1284 
This is another set of tests that falsely assumed that Noisepage and Postgres would return identical tuple orders on unsorted data.  To fix this, this PR removes hashed results which are both hard to debug and implicitly assume a sort order, and instead relies on the "rowsort" option (replacing "nosort") to force the sorting of both the result set and expected in Java.
Additionally, this PR includes the original SQL file along with the command to generate it to facilitate any future updates or new tests in the future.
This appears to be a larger issue throughout all of the tracefiles and probably needs a to be replicated across the other JUnit tests.

Fix update.test Tracefile

---

Jenkinsfile-nightly

This adds a loop that will run the microbenchmark data 4 times each night. This will add 1:30 to the nightly job. This means that the nightly build will run from ~2 am - 6 am. If merged today we should have enough data by Monday, at which point I can remove the loop from the Jenkinsfile.
Here is proof that it works: http://jenkins.db.cs.cmu.edu:8080/blue/organizations/jenkins/testing-team%2Fterrier-nightly/detail/populate-microbench-data/5/pipeline
Once we have 20 entries in the database (currently at 7) I will remove this change.

Populate Microbenchmark Data

---

src/include/planner/plannodes/update_plan_node.h

The indexed_update_ variable is not set according to the passed in parameter, but always to true. Fixed it by letting indexed_update_ adopt the boolean value passed into this function.

fix typo in SetIndexedUpdate in Update Plannode

---

src/optimizer/index_util.cpp
test/catalog/catalog_sql_test.cpp

Fixes #1132 
The optimizer was implicitly assuming that all indexes supported all modes of querying.  Therefore, it would create plans that called for range scans on hashmap indexes and cause the system to crash at runtime.  This PR inserts a check inside `IndexUtil::CheckPredicates` that ensures we force a negative response if the predicate would require this situation.
Ideally, this should be a more general check which allows adding additional index types like PostgreSQL does.  However, that would require implementing several more catalog tables and logic to have the optimizer query that information when checking predicates.

Prevent optimizer from issuing plans with range scans on hashmap indexes

---

docs/README.md
docs/dev_troubleshooting.md

Recently, my local development setup for NoisePage stopped working. Whether this was a result of the updates to the build configuration or updates on my side, it seems prudent to document the errors I encountered while re-configuring my system for local development to (hopefully) save future developers some time. To this end, I created a new document in the `docs/` directory for the purpose of maintaining information related to development environment troubleshooting. This document should be extensible to allow others to update it going forward as further issues are encountered and subsequently resolved.
None
N/A
None

Development Environment Troubleshooting Documentation

---

CMakeLists.txt

For test parallelism to work, each test that hogs some common resource (network ports, paths to some files, etc) must declare it [here](https://github.com/cmu-db/noisepage/blob/240dc30eb9874f27dd2e88a7e380274c5de44072/CMakeLists.txt#L998).
`catalog_sql_test` was added in a recent PR. I'm not sure where to document this so that everyone writing tests that manually bring up `DBMain` and `RunServer()` (hopefully uncommon and limited to stuff which can't go through SQL trace files) can find it. Ideas for where to document this?
No point sending this through CI.

Add port resource constraints to catalog_sql_test.

---

script/testing/junit/src/GenerateTrace.java

When generating a test trace file, if there's an error executing the SQL statement (either syntax or any other), then it will fail silently and cause a NullPointerException later on. This commit just adds an error message that makes it easier to debug when GenerateTrace fails. Note, this doesn't actually cause it to fail any earlier and it will still fail with a NullPointerException later on, it just adds an error message earlier.
The one downside is that if you are creating a test where you expect a lot of errors then the output will be a little noisy. I think it's a worthwhile trade-off because generating a trace is usually just a one time activity so a noisy output isn't a huge deal, especially if you're expecting sql statements to fail. Let me know thoughts in the comments.
N/A
N/A …

Add error message when GenerateTrace fails

---

docs/dev_troubleshooting.md

I was experiencing issues wherein attempting to disable Asan's container overflow checks with an environment variable would fail when running or debugging the application from within CLion - the IDE appears not to respect the environment variable for some reason (no matter how hard I tried to make it...). Fortunately, CLion provides another way to set options for various sanitizers that I just came across. This PR just adds this finding to the troubleshooting documentation.
None.
N/A
None

Add documentation for preventing Run / Debug from CLion from crashing on ASAN Container Overflow

---

script/testing/junit/traces/select.test
src/binder/bind_node_visitor.cpp
src/binder/binder_util.cpp
src/include/parser/expression/type_cast_expression.h
src/include/parser/expression_util.h

Fix #1219.
This enables `::` casting and also allows for `select true` which I believe @tanujnay112 may have wanted?
I think `::`-casting worked in the past because we pulled out the TypeCastExpression's contents, which is behavior that was probably rolled back with the binder cleanup (sherpa). This PR brings that back with the justification of Postgres not allowing you to do anything interesting in casts, as far as I can tell:
```
postgres=# select '1+1'::bigint;
ERROR:  invalid input syntax for type bigint: "1+1"
LINE 1: select '1+1'::bigint;
^
postgres=# select cast('1+1' as bigint);
ERROR:  invalid input syntax for type bigint: "1+1"
LINE 1: select cast('1+1' as bigint);
^
postgres=# \errverbose
ERROR:  22P02: invalid input syntax for type bigint: "1+1"
LINE 1: select cast('1+1' as …
```

Add support for type cast expressions.

---

src/include/storage/data_table.h

The `accessor_` member of `DataTable` was made public during the course of rewriting the `SlotIterator` which exposes internal storage layer APIs to the rest of the system.
This makes `accessor_` private again and adds `AccessObserver` and `ArrowSerializer` as "friends" to `DataTable` in order to allow them the privileged access they currently use in their implementations.

Make DataTable::accessor_ private

---

script/testing/junit/traces/select.test
src/execution/compiler/expression/comparison_translator.cpp
src/execution/compiler/operator/seq_scan_translator.cpp
src/parser/postgresparser.cpp

Fix #1221 by adding support for the SQL IN operator in WHERE clauses.
- `... WHERE foo IN (1)` will be treated the same way as `foo = 1`, including vectorized stuff.
- `... WHERE foo IN (1,2,...,N)` will be treated as `(foo = 1) OR (foo = 2) OR ... OR (foo = N)`.
Also fixes some tables not getting dropped in `select.test`. And adds a couple of tests.
Just picking random things off the TPC-H list. We're actually very close.
Will flip to ready-for-review if passes CI.

Add support for SQL IN operator in WHERE clauses.

---

src/execution/exec/execution_settings.cpp
src/include/common/constants.h

We had a `parallel_execution` setting described as "Whether parallel execution for scans is enabled" which does not work as described. This is because it wasn't connected to the `SettingsManager`.
I notice some CI pipelines are setting this flag -- specifically `tpcc_parallel_disabled` -- parallel scans should really be disabled for real now.
I don't know how to write tests for this. If we had EXPLAIN tpl, this would work:
```
CREATE TABLE foo (a int);
/** By default, parallel execution is on. */
EXPLAIN tpl SELECT * FROM foo;  /** Test that ParallelWork in output. */
SET parallel_execution TO false;
EXPLAIN tpl SELECT * FROM foo;  /** Test that SerialWork in output. */
SET parallel_execution TO true;
EXPLAIN tpl SELECT * FROM foo;  /** Test that ParallelWork in output. */
```
Right now, …

Fix SET parallel_execution which was not hooked up to execution.

---

script/testing/junit/traces/select.test
src/parser/postgresparser.cpp

I thought it was weird that we didn't support IN. We do as of #1326, I think @gautam20197 you may have been running an old version.
Then I thought it was weird that IN and NOT IN returned exactly the same results.
```
noisepage=# select * from foo where a in (2);
a 
---
1
noisepage=# select * from foo where a not in (2);
a 
---
1
```
Then I realized I didn't remember ever seeing anything related to NOT IN in the codebase.
And that's because both IN and NOT IN comes in from the Postgres parser as a AEXPR_IN expression with almost everything identical -- you distinguish between the two by the name.
IN is called "=" and NOT IN is called "<>".
I expect this to pass CI, marking ready for review.

Add support for NOT IN.

---

script/testing/artifact_stats/README.md
script/testing/artifact_stats/collectors/__init__.py
script/testing/artifact_stats/collectors/binary_size.py

New collector to keep track of the size of our binary in the nightly builds. This is to make sure that we don't balloon up the size of our binary over time. This resolves #1365.
https://youtu.be/X_p6HLNNfl0

Artifact Stats: Binary Size Collector #1365

---

script/testing/junit/traces/update.test
src/execution/compiler/operator/update_translator.cpp
src/optimizer/plan_generator.cpp
test/optimizer/tpcc_plan_delivery_test.cpp
test/optimizer/tpcc_plan_neworder_test.cpp
test/optimizer/tpcc_plan_payment_test.cpp

Fix #1366, which indicates an error with respect to how set clauses are codegen'ed. This PR fixes the issue by codegen'ing the SET clauses to refer to the original tuple (i.e the tuple presented by the child plan node). For columns that are not updated by any SET clause, the value from the original tuple is copied into the new tuple.

Fix UPDATE behavior when SET clauses reference other columns.

---

Jenkinsfile
script/installation/packages.sh

Hardcode LLVM_DIR to llvm@8 path on OSX.
brew is generally fragile as part of a build system, sometimes making
changes that require us to update the template VM images that we run on.
We will now move towards installing brew from scratch.
This is problematic in Jenkins because the setting of environment variables
happens before the packages.sh install step.
Since we don't update LLVM_DIR often, we might as well hardcode it.
go jenkins go

Hardcode LLVM_DIR to llvm@8 path on OSX.

---

src/include/binder/sql_node_visitor.h
src/include/network/network_defs.h
src/include/network/network_util.h
src/include/parser/parser_defs.h
src/include/parser/postgresparser.h
src/include/parser/statements.h
src/include/parser/variable_show_statement.h
src/include/traffic_cop/traffic_cop.h
src/network/postgres/postgres_network_commands.cpp
src/network/postgres/postgres_packet_writer.cpp
src/parser/postgresparser.cpp
src/traffic_cop/traffic_cop.cpp
src/traffic_cop/traffic_cop_util.cpp

This adds "support" for SHOW TRANSACTION ISOLATION LEVEL, which postgres translates as SHOW transaction_isolation.
This does **NOT** implement a general-purpose SHOW, which should talk to the settings manager.
Nor does it reconcile the fact that some SET and SHOW should be transactional (as found by @Poojita-Raj).
This is purely to unblock @AlanDZQ for his oltpbench stuff.
The rest of the work is left for #1188.
If it gets through CI, then ready for review.

Implement a hacky version of SHOW for transaction_isolation.

---

script/testing/oltpbench/test_oltpbench.py
script/testing/oltpbench/utils.py
script/testing/util/common.py
script/testing/util/db_server.py
script/testing/util/test_server.py

This fixes #1384. The server args string was not getting created correctly. This fixes the issue with boolean server args. Also, when the DB instance starts it prints the full start command along with the arguments. 
I also took a quick pass at adding `dry-run`, it ended up being much simpler than I thought. I implemented it so that the DB server starts and prints its starting command and then stops, without doing anything. Here is the output.
```
root@2adc8c73e54d:/repo/build# python3 ../script/testing/oltpbench/run_oltpbench.py --config-file=../script/testing/oltpbench/configs/nightly/nightly_wal_disabled.json --build-type=release --dry-run
12-09-2020 17:33:08,998 [common.py:36] INFO : ****** start killing processes on port 15721 ******
12-09-2020 17:33:08,998 [common.py:36] INFO : …
```

Fix passing false arguments to testing scripts. Add dry-run functionality.

---

Jenkinsfile
Jenkinsfile-nightly
script/testing/lsof.sh

Add calls to lsof in Jenkins.
Before and after everything that might spawn a NoisePage instance.
This is to catch any stray processes leftover from before our run, or lingering after our run.

Add calls to lsof in Jenkins.

---

script/testing/junit/traces/insert.test
src/binder/bind_node_visitor.cpp

Fix iterator invalidation in binding insert statements.
Fix #1408.
The list of column names to insert into was getting iterator-invalidated.

Fix iterator invalidation in binding insert statements.

---

src/network/README.md
src/network/postgres/postgres_network_commands.cpp

Add guide comments to network folder's README.
I was poking around in the `network` folder earlier and thought that something like this would have been helpful:
- for people who've poked around before, a refresher of how things work
- for new people, a guide to where to look
Just documentation, no point going through CI.

Add guide comments to network folder's README.

---

Jenkinsfile

This is just a small PR for some work that should have been part of #1368 but must have gotten lost on one of my merges. It just sends the performance data from the normal PR pipeline to our performance storage service. This is needed to enable the performance cop.
Here is proof of a passing build: http://jenkins.db.cs.cmu.edu:8080/blue/organizations/jenkins/testing-team%2Fterrier/detail/ci-performance-reporting/3/pipeline/287

add reporting to terrier build

---

test/messenger/messenger_test.cpp

Add a spin-until-initialized to messenger_test to avoid races.
Fix #1319 (I think).
Previously, it was possible in `BasicListenTest` for the replica to try to connect to the primary before the primary had opened an additional listening channel on port 8030.
This adds a dirty spin-on-shared-memory-until-things-are-ready hack. In general, I'm not too happy with how testing multiple processes in C++ works -- forking more than one child means that you lose the debugger autoattach (though you can still manually attach), coordinating between the processes is not so good either.
I notice that I can't seem to set the SO_REUSEADDR property on the zeromq sockets.
The `DirtySleep` gets around that by waiting for what should be long enough for the test to work without address reuse.

Add a spin-until-initialized to messenger_test to avoid races.

---

src/include/self_driving/model_server/model_server_manager.h

Fix missing includes in model_server_manager header.
Fix #1406.
The underlying cause is that the model server manager header is missing some includes which the previous `#include` items were providing.
---
Apparently github has video support for pull requests now.

Fix missing includes in model_server_manager header.

---

script/testing/junit/traces/nested-query.test
src/include/optimizer/rules/unnesting_rules.h
src/optimizer/rules/rewrite_rules.cpp
src/optimizer/rules/unnesting_rules.cpp

Part of RewritePullFilterThroughAggregation and DependentSingleJoinToInnerJoin rules rule adds a group by column to the aggregation from one of the sides of the predicate. When selecting a column we need to make sure that the column is at the same depth as the aggregation or deeper. If the group by column is part of the outer query and the aggregation part of the inner query, then the aggregation has no way of accessing the column. A higher value for depth means deeper in the querer and a lower value for depth means more shallow in the query. The current code was always setting the column from the left side of the predicate as the group by column. This was sometimes causing the group by column to be more shallow than the aggregation itself which caused the query to error out.
Fixes #1404 …

 Fix correlated subquery optimizer rules

---

test/execution/sql_filter_manager_test.cpp

Increase the fake sleep in AdaptiveCheckTest.
Fix #1378.
I don't know why `FilterManager.AdaptiveCheckTest` has become more flaky nowadays.
This just builds on @gonzalezjo's previous fix in #1085 by upping the fake sleep time from 250us to 500us, so hopefully that test becomes more reliable.
I don't particularly see a point in running this through CI.

Increase the fake sleep in AdaptiveCheckTest.

---

script/model/data_class/grouped_op_unit_data.py
src/include/self_driving/modeling/operating_unit_defs.h
src/self_driving/modeling/operating_unit_recorder.cpp

We don't model the LIMIT operating unit since it does not have its own operator. But we still record this OpUnit in the `OperatingUnitRecorder`, which causes inference error unless we skip it manually. This PR skips recording the LIMIT OpUnit in `OperatingUnitRecorder`.

Skip recording the un-modeled LIMIT operating unit

---

script/testing/junit/traces/insert.test
src/binder/bind_node_visitor.cpp
src/include/catalog/schema.h

Postgres lets you do this:
```sql
matt=# create table foo (id int default '1');
CREATE TABLE
Time: 9.845 ms
matt=# insert into foo values (default);
INSERT 0 1
Time: 1.021 ms
matt=# select * from foo;
id 
----
1
(1 row)
Time: 0.248 ms
```
Basically you can have a default value that is not the same type as the schema column. It gets cast at insert time, which can be verified by setting a default that doesn't actually work. Postgres also lets you do this:
```sql
matt=# create table foo (id smallint default 3429089082);
CREATE TABLE
Time: 1.317 ms
matt=# insert into foo values (default);
ERROR:  22003: smallint out of range
LOCATION:  int82, int8.c:1313
Time: 1.315 ms
```
We now match this behavior. This was found while trying to run Wikipedia via oltpbench using the Postgres DDL.
- Relax …

Fix default values of mismatched types

---

src/include/storage/write_ahead_log/log_io.h
src/storage/write_ahead_log/disk_log_consumer_task.cpp

This PR adds an optimization in `DiskLogConsumerTask` to avoid calling `BufferedLogWriter::Persist()` if no bytes have actually been written.
Currently, if WAL is enabled then the `DiskLogConsumerTask` hammers the `fdatasync` system call (via `BufferedLogWriter::Persist()`) based on a timeout. There's no reason to perform this system call if no bytes have been written, and this ends up on the critical path to read-only transaction COMMITs.
I first noticed this a few months ago when spinning up the system and noticing that the disk activity light on my NUC was going crazy even when the DBMS is idle and not writing any data, but punted until recently exploring read-only transaction bottlenecks.
One-line change in`DiskLogConsumerTask` to add a check if the number of bytes the number of bytes …

DiskLogConsumerTask avoids calling Persist() if no data written

---

script/installation/packages.sh
script/testing/microbench/README.md
script/testing/microbench/artifact_processor.py
script/testing/microbench/micro_benchmarks_runner.py

Matt found a mistake in the % change calculation on the dashboards so I audited all the percentage change calculations. I found I made the same mistake with the microbenchmark script. The impact is minimal as this is only really used when the results are printed out in the terminal. While I was fixing the mistake I figured I would improve the documentation for the files that I touched. Now they follow the numpydocs formatting. If anyone wants to double check that % change is calculated correctly here is a snippet of the output. 
No impact
None

Microbenchmark fix %change mistake

---

benchmark/benchmark_util/data_table_benchmark_util.cpp
benchmark/integration/tpcc_benchmark.cpp
benchmark/storage/block_compactor_benchmark.cpp
benchmark/storage/index_wrapper_benchmark.cpp
src/include/main/db_main.h
src/include/settings/settings_defs.h
src/include/transaction/transaction_manager.h
src/transaction/transaction_manager.cpp
test/network/network_test.cpp
test/optimizer/logical_operator_test.cpp
test/optimizer/optimizer_context_test.cpp
test/optimizer/physical_operator_test.cpp
test/storage/block_compactor_test.cpp
test/storage/export_table_test.cpp
test/traffic_cop/traffic_cop_test.cpp

This PR implements something similar to Postgres' [asynchronous commit WAL setting](https://www.postgresql.org/docs/current/wal-async-commit.html), albeit not at a per-transaction granularity as Postgres allows.
Currently, if WAL is enabled then on transaction COMMIT the `TransactionManager` pushes a transaction's `CommitRecord` down to the `LogManager`, which in turn pushes it to the `DiskSerializerTask`. Once a transaction's records are serialized, it is removed from the running transactions table by the `DiskSerializerTask`, and then the callback is pushed to the `DiskLogConsumerTask`. Finally, once a transaction's records are persisted to disk (via `fdatasync`) its callback can be invoked and the client receives an acknowledgement of COMMIT. This coordination is expensive for …

Added wal_async_commit_enable setting, defaulted to false

---

Jenkinsfile
benchmark/integration/tpcc_benchmark.cpp
benchmark/metrics/garbage_collection_metrics_benchmark.cpp
benchmark/metrics/large_transaction_metrics_benchmark.cpp
benchmark/metrics/logging_metrics_benchmark.cpp
benchmark/runner/mini_runners.cpp
benchmark/runner/tpcc_runner.cpp
benchmark/runner/tpch_runner.cpp
benchmark/runner/transaction_logging_gc_runner.cpp
src/include/main/db_main.h
src/include/metrics/metrics_manager.h
src/include/metrics/metrics_store.h
src/include/settings/settings_callbacks.h
src/include/settings/settings_defs.h
src/metrics/metrics_manager.cpp
src/metrics/metrics_store.cpp
src/self_driving/pilot/pilot.cpp
src/settings/settings_callbacks.cpp
test/integration/tpcc_test.cpp
test/metrics/metrics_test.cpp

Change metrics sampling interval to a sampling rate based on %.
I need to change pipeline metrics sampling at a finer granularity than currently offered with the interval implementation.
There's a new setting to replace the interval. Default value is 10% just like the current sample interval of 9. Refactored tests and pilot. There's a side effect that it takes 100 queries to see this sample rate, rather than the old interval method. For example, if you set a sample rate of 10%, and run 10 queries, you may not see any samples generated. This is because the samples are distributed randomly in a bitset of 100 values, so it can take 100 samples to get the 10 you expect for 10% sampling.

Change metrics sample interval to a sample rate [0,100]

---

src/self_driving/model_server/model_server_manager.cpp

Currently, if the main DBMS thread dies unexpectedly (e.g., crashes) when the model server is enabled, the Python model server process would become a zombie. And we have to kill it manually. This PR registers a parent death signal to the model server child process, so the model server is killed when the parent dies.
**Caveat**: This PR uses `prctl`, which only works on Linux. This won't work on macOS, but we don't support macOS anyway...

Kill forked model server upon parent NoisePage process death.

---

script/model/model_server.py

We're not setting up the model map key correctly in the model server so we never cache the model maps. This PR fixes this problem.
This should accelerate the OU model inference through the model server significantly, which is especially useful for @rabbit721's work on the pilot.

Proper model caching in model server

---

src/self_driving/model_server/model_server_manager.cpp

I removed this include in #1459 since Linux doesn't need this. But apparently, macOS requires `<csignal>` to find `::kill`. Even though we officially don't support macOS anymore, right now we can still compile on mac. So I'm adding this back.

Add back <csignal> include to model_server_manager.cpp

---

script/testing/artifact_stats/base_artifact_stats_collector.py

In a PR comment, changed inheritance from `object` to `ABC` but forgot to import it.

Fix missing artifact stats import.

---

Jenkinsfile-nightly
script/testing/util/db_server.py

Fix nightly oltpbenchmark and microbenchmark builds.
Attempt to fix nightly build.
- Add wait to DBServer stop. I think it was racing between sending the terminate signal to the old process (and not waiting for that to die), and the next iteration of the OLTPBenchmark run, which would cause the new DB process to die since it couldn't grab the port.
- No longer log useless lines.
- Fix path issues for nightly microbenchmark.

Fix nightly oltpbenchmark and microbenchmark builds.

---

CMakeLists.txt
build-support/generate-bitcodes.sh

As the conversation below indicates, updates that I made in a previous PR lead to issues with parallel builds. Specifically, the changes I introduced made it so that multiple top-level targets depend on generation of the bytecode handlers file, `bytecode_handlers_ir.bc` (e.g. one of the execution jumbotests and the TPL runtime are not interdependent, but both depend on generating the bytecode handlers). This leads to concurrency issues in parallel builds wherein the script that is responsible for compiling the bytecode and subsequently optimizing it fails to locate a temporary file upon which it depends because it has been renamed / overwritten by a concurrently-running invocation of the custom command. Gross.
The (proposed) fix here is pretty simple, and follows in that great computer …

Hotfix for CI Builds.

---

src/execution/exec/output.cpp
src/include/execution/exec/output.h

Found this will looking at instrumenting the output layer. We shouldn't be using `SpinLatch` for operations longer than ~20 instructions (per Intel). Since writing to the network layer for a large number of tuples is definitely going to involve sys calls and more instructions than that, we should favor a `std::mutex` for synchronization here.

Favor std::mutex over SpinLatch for OutputWriter synchronization.

---

script/testing/junit/__main__.py
script/testing/junit/src/TracefileTest.java
script/testing/util/db_server.py
script/testing/util/test_server.py

Delete domain socket on DBMS shutdown. Clarify junit tracefile reporting.
Normally when you spin up a DBMS we get the network socket and then the domain socket.
```
[2021-02-19 11:50:54.637] [network_logger] [info] Listening on networked socket with port 15721 [PID=3372]
// my PR got stuck here
[2021-02-19 11:50:54.637] [network_logger] [info] Listening on Unix domain socket with port 15721 [PID=3372]
```
I noticed that one of my CI runs was failing because it couldn't get the domain socket, so this PR will try to delete the domain socket if it exists when the DBMS is stopped. In theory our DBMS startup code already does this but `¯\_(ツ)_/¯` maybe this helps.
Also, good news: we're _not_ running the tracefiles a million times, the scripts were just opening `junit_log.txt` in append "a+" …

Delete domain socket on DBMS shutdown. Clarify junit tracefile reporting.

---

CMakeLists.txt

Add ninja job pools to limit link parallelism.
Staring at replication not go through CI and noticing that the junit stuff starts being very slow (slow to startup db, slow to finish test, hits the timeout) when another node on the same machine (h3) is busy running a huge parallel link.
This PR restricts linking to be single-threaded. Specifically, the job pools are sized:
```
num logical cores = compile pool + link pool (1) + 1
```
where the 1 is just there as a good luck safety buffer thing. You can re-read that as
```
link: single-threaded
compile: num logical cores - 1 for the link - 1 for good luck
```
Anecdotally, this seems to OOM my local machine less.
This is also an advantage of ninja, afaik make does not have convenient ways of limiting link parallelism.

Add ninja job pools to limit link parallelism.

---

script/testing/util/db_server.py

Log DB server output in all runs.
Some additional logging code to get DB server output on script/testing runs.
Not super clean (overlapping message with `print_db_logs`), but not too terrible.

Log DB server output in all runs.

---

src/self_driving/pilot/mcts/monte_carlo_tree_search.cpp

#1475 added a loop iterator that is only used for debug logging. This breaks builds that have `NOISEPAGE_USE_LOGGING=OFF`, which I do for my performance testing.
This PR adds the `UNUSED_ATTRIBUTE` macro to the iterator.

Fix NOISEPAGE_USE_LOGGING=OFF compilation

---

Jenkinsfile

Per @malin1993ml ,
> Another minor CI improvement I've been thinking is that maybe we can set ubuntu-20.04/gcc-9.3 (Debug/Coverage/unittest) to always run on h0 . It is building 3x more targets than other builds, and seems always to be the bottleneck in our Test stage.
This is done by introducing a new `h0-only` label to h0, and manually specifying that this specific job can only execute on nodes with the `h0-only` label.

Switch gcc/Debug/Coverage/unittest to only use h0.

---

src/include/storage/index/bplustree.h

Fix bplustree.h redefined constant shared with bwtree.h.
Some PRs are failing CI due to `#define` definition leaking in some unity builds, and I think we'd like to avoid random define pollution in headers anyway.

Fix bplustree.h redefined constant shared with bwtree.h.

---

script/testing/microbench/benchmarks.py
src/include/storage/index/bplustree.h

Fix for BPlusTree test failures
The MultiThreadedInsert test in BPlusTree was broken due to an error in StructuralIntegrityVerification. This was because of inaccurate thresholds mentioned for splitting and merging a node. This PR also adds `bplustree_benchmark` to the list of microbenchmarks run by the stats script.
The correct thresholds are:
* FAN_OUT :  128
* Minimum Keys in Inner Node:  63 [Ceil (FAN_OUT / 2) - 1]
* Minimum Keys in Leaf Node:  64 [Ceil ((FAN_OUT - 1) / 2)]

Fix for BPlusTree test failures

---

Jenkinsfile
build-support/print_docker_info.sh

Jenkins: Move microbenchmark building to pre-test and on any node. Add print_docker_info.sh.
Since microbenchmarks are only built and are not run,
- We might as well build them earlier. This avoids people having their builds pass the test stage, only to fail some microbenchmark compilation error and have to go through CI again.
- We don't need a dedicated benchmark machine just to compile the code.
This PR also adds a script `build-support/print_docker_info.sh` to print image name, uptime, current time, to check if we're somehow executing on a different left-behind docker image. This hopes to provide data for weird `mkdir build` failures.
Run through CI.

Jenkins: Move microbenchmark building to pre-test and to any node. Add print_docker_info.sh.

---

docs/dev_troubleshooting.md

Add guide to getting debug symbols on clang.
On GCC, you can view the values of a `std::string` in the debugger.
On clang, you can't. This is because clang assumes `libstdc++` will provide it.
You can invalidate that assumption by passing a compiler flag but that makes the binary bigger and linking slower.
So if you want to easily debug things like `std::string`s when compiling with clang, you should install debug symbol packages.

Add guide to getting debug symbols on clang.

---

docs/dev_troubleshooting.md

There were some missing steps from the initial PR. @lmwnshn caught one. This adds the other.

Add missing step from Ubuntu wiki from #1507

---

src/include/storage/index/bplustree_index.h
src/storage/index/bplustree.cpp
src/storage/index/bplustree_index.cpp

Forward declare the `BPlusTree` and remove its include from the `bplustree_index.h` header, instead moving it to the implementation file `bplustree_index.cpp`. Though it doesn't currently leak into too many other files via include, this will prevent it in the future from hurting compilation time.

Forward declare BPlusTree

---

Jenkinsfile
Jenkinsfile-utils

jenkinsfile-utils wasn't updated when #1426 renamed the e2e test build option, so we've had:
```
CMake Warning:
Manually-specified variables were not used by the project:
NOISEPAGE_BUILD_SELF_DRIVING_TESTS
```
in every CI build since then.

fix Jenkinsfile-utils for self-driving e2e tests

---

script/testing/junit/__main__.py
script/testing/util/db_server.py
script/testing/util/test_server.py

Check for DBMS exit codes in CI's script.testing.junit.
Fix #1483.
The issue was that DBMS exit codes were not being checked.
This should fail CI until #1482 merges.
This should be merged before #1111.

Check for DBMS exit codes in CI's script.testing.junit.

---

CMakeLists.txt

This upgrades fast float to the first major release version. I don't plan on monitoring the releases of fast float anymore, I just wanted to upgrade to a major version when one came out.

Upgrade fast float to major version

---

Jenkinsfile

The tests include the c++ coverage test and the modeling coverage test for self-driving. Also, add the artifact report for the modeling test.

Jenkins: rearrange coverage tests to run on the more performant 'dgb' machine group

---

script/self_driving/model_server.py
src/self_driving/model_server/model_server_manager.cpp

The improper model serve caching was fixed in #1458, but then later on broke due to a merge conflict. This fixes the broken line.
It's a one-line fix so I don't think this needs to go-through CI.

Re-fix model server cache due to merge conflict

---

script/testing/artifact_stats/collectors/binary_size.py

In PR [#1470](https://github.com/cmu-db/noisepage/pull/1470) I refactored some of the Python testing scripts. What I neglected to account for in this refactor is the fact that some (in this particular case, one) function I modified was imported and used in another script run in the nightly artifacts collection. I changed both the name and the semantics of the function, resulting in a runtime failure when the nightly artifacts stats collection was run in the nightly CI pipeline. This PR fixes this issue by updating the binary size artifact collection script to use the updated function.

fix broken import in binary size artifacts collection script

---

docs/tech_clion.md

Add documentation for attaching to existing processes in CLion.
Just a useful command that I've been making frequent use of recently. Then you get to use CLion's nice wrapper around GDB.

Add documentation for attaching to existing processes in CLion.

---

script/testing/.gitignore
script/testing/microbench/micro_benchmarks_runner.py

This PR does three things:
* Strip debug statements from our system in the JSON output of the microbenchmarks.
* Fixes the environment variables that we weren't setting correctly for the # of CPU cores + log path.
* Adds a gitignore to hide the microbenchmark output files.
https://youtu.be/iin3ZVXot74

Nightly Microbenchmark JSON Fixes

---

script/testing/util/db_server.py

The WAL file location can be specified as either a relative path or an absolute path. In our test framework, we often start instances of the database with the WAL enabled, and after the test we attempt to delete the WAL. The test framework was only successfully deleting the WAL when it was specified as an absolute path, so this PR adds the functionality to delete the WAL when it's specified as a relative path.

Delete WAL in tests if it is specified as a relative path

---

script/testing/junit/traces/select.test
src/binder/bind_node_visitor.cpp
src/binder/binder_util.cpp
src/include/binder/binder_util.h
src/optimizer/statistics/stats_calculator.cpp

@abigalekim #1234 identified an issue with `WHERE` clauses that don't reference columns. If it's a literal or arithmetic expression things go kaboom, in a few different places. This fixes immediate errors in the `stats_calculator` for selectivity, adds a helper method in the Binder to verify a `WHERE`'s return type, and adds a couple of tests.
The simplest of literals are still broken though. I'll open an issue for that since it's a big rabbit hole.

Binder catches WHERE clause with incorrect return type

---

src/include/settings/settings_defs.h

Changes the description of the port setting from "Terrier port (default: 15721)" to "NoisePage port (default: 15721)". 
Note: The `model_save_path` setting still uses terrier for the default path. I don't know enough about this property to feel comfortable changing it though. If the reviewer thinks that it's fine to change that property, I can include it in this PR.

Rename port setting from Terrier to NoisePage

---

script/testing/util/db_server.py

When running the database through our python scripts there is a hardcoded timeout of 600 seconds. After waiting for the DB to startup for 600 seconds the script times out and returns an error.
I think for some use cases 10 minutes is a bit excessive to wait and we may want to timeout much sooner. To solve this I added an optional timeout parameter that defaults to 600 seconds. All existing scripts will be unchanged, but those in the future who want to set a smaller timeout can do that.
Sorry for the formatting changes, I format all the files I'm working on out of habit. If it's an issue I can go through and revert all the formatting changes.

Add configurable timeout to run db script

---

src/include/main/db_main.h
src/include/settings/settings_defs.h

Add -async_replication_enable command line arg.
Add -async_replication_enable command line arg.
This arg has no effect unless -replication_enable is also provided,
in which case it defaults to async replication instead of sync replication.
Minimum set of flags: `-messenger_enable -replication_enable -async_replication_enable`

Add -async_replication_enable command line arg.

---

script/testing/util/db_server.py
src/execution/vm/llvm_engine.cpp

Port LLVMEngine::Optimize to skip module passes.
Copies over Prashanth's commit here:
https://github.com/pmenon/tpl/commit/e2d3749032d81a9792d9b8a2e82569d063ebd1ad#diff-ed4b8c2805fa1b88ccfdd18b72ce7eebaf3485e63bf95990c7551716a9d79a5f
Unscientific timing on a separate branch showed that much
more time was spent running module passes than the singular
inlining function pass, so maybe this will help. In general, we
also would like to have function passes (as opposed to module)
wherever possible so that it is easier to time the passes.
And for a few hand-checked examples, function optimize time went up (as expected),
but overall optimize time went down.
Expect to see a speedup in the compiled tests on CI.

Port LLVMEngine::Optimize to skip module passes.

---

Jenkinsfile-utils.groovy

Invoke ninja instead of ninja noisepage so that microbenchmarks are built.
Should fix the nightly build. One-liner, just going to merge and rerun.

Invoke ninja instead of ninja noisepage so that microbenchmarks are built.

---

src/include/transaction/transaction_context.h

This commit allows the database to run with synchronous durability but asynchronous replication. The benefit of this is that you can run with synchronous durability and replication turned on without taking some of the performance penalties associated with synchronous replication.
As the comment suggests there is a potential for data loss if the primary crashes and one of the replicas is promoted to primary (though this promotion functionality isn't implemented yet)
All results performed under TPCC with a scale factor of 1
13.198780362740948 requests/sec
96.29715975379193 requests/sec

Allow sync durability with async replication

---

src/catalog/catalog_accessor.cpp
src/catalog/database_catalog.cpp
src/catalog/postgres/pg_constraint_impl.cpp
src/catalog/postgres/pg_core_impl.cpp
src/catalog/postgres/pg_language_impl.cpp
src/catalog/postgres/pg_proc_impl.cpp
src/catalog/postgres/pg_statistic_impl.cpp
src/include/catalog/database_catalog.h
src/include/catalog/index_schema.h

The only real logic change is that we were dumping columns for a new table into `pg_statistic` before we validated that creating the new table would even succeed. We should try to be more defensive in the catalog and not assume that operations will succeed.
Otherwise I just did my usual style nit fixes, trying to to focus on `const &` where we're currently doing deep copies on STL data structures that aren't changed in the local scope. I wish clang-tidy would yell at us about that.

Minor Catalog refactors

---

src/include/replication/replication_messages.h
src/replication/replication_messages.cpp

This PR switches our message serialization implementation for replication from JSON to Message Pack.
See #1570 for more details
(Scale factor 1, 8 threads)
| Replication | Durability | Reqs per second |
|-----------	|-------------- |-----------------------	|
| Sync | Sync | 13.19878036 |
| Async | Sync  | 96.29715975 |
| Async | Async | 225.1782607 |
| Disabled | Sync | 208.8917964 |
| Disabled | Async | 259.5795886 |
(Scale factor 1, 8 threads)
| Replication | Durability | Reqs per second |
|-----------	|--------------	|-----------------------	|
| Sync | Sync | 16.099501826675176 |
| Async | Sync  | 230.38818864265522 |
| Async | Async | 223.0805671394837 |

Switch Replication Messages to Message Pack

---

src/traffic_cop/traffic_cop.cpp

Add explicit cast to initialize TrafficCopResult for EXPLAIN.
Had to add this to make my compiler happy in Release mode.
`-- Compiler: /usr/bin/clang++-8 Clang 8.0.1`
Explicitly cast a 0 as unsigned to help some compilers along.

Add explicit `u` suffix to initialize TrafficCopResult for EXPLAIN.

---

src/include/self_driving/forecasting/forecaster.h
src/include/self_driving/planning/pilot.h
src/self_driving/forecasting/forecaster.cpp
src/self_driving/planning/pilot.cpp

We have quite some workload forecasting code that doesn't belong to the core `Pilot` logic, but is mixed in the `Pilot` class. This PR separates that code into its own `Forecaster` class so that the logic in `Pilot` is cleaner.

Refactor workload forecasting logic in Pilot to a separate Forecaster class

---

CMakeLists.txt
Jenkinsfile-utils.groovy
build-support/run-clang-tidy.py
build-support/run_clang_tidy_extra.py
src/execution/sql/thread_state_container.cpp

Run check-clang-tidy-full on master build.
Adds `check-clang-tidy-full` target that skips applying the git filter which we introduced in #741.
The motivation is that we may sometimes hammer "Retry test from stage" on a PR through CI, which means that we could skip running clang-tidy on the contents of later commits.
- Run 1 is as-is in the PR: http://jenkins.db.cs.cmu.edu:8080/blue/organizations/jenkins/terrier/detail/PR-1567/1/pipeline
- Run 2 is manually replayed with alternative code to show that the else branch works: http://jenkins.db.cs.cmu.edu:8080/blue/organizations/jenkins/terrier/detail/PR-1567/1/pipeline

Run check-clang-tidy-full on master build.

---

src/optimizer/statistics/selectivity_util.cpp

There's a small bug in the stats optimizer that causes my build to not work locally--fixed by adding template to std::min. (putting in separate pull request for modularity's sake).
None.
None.
None.

Small fix to compile on Mac (note that we do not support Mac builds).

---

script/testing/junit/traces/functions.test
script/testing/junit/traces/select.test
src/execution/vm/bytecode_generator.cpp
src/network/postgres/postgres_packet_writer.cpp

Port TPL behavior for float literals. Change print behavior for REAL.
@tpan496 found a bug where values outside of float range were treated as 0 or inf.
We were casting doubles down into floats in the `bytecode_generator`.
Something we missed when porting TPL2 and making the "64-bit instead of 32-bit by default" change.
It's another one of those "fixed in TPL" things so I went and yoinked that code.
This also changes the default behavior of printing real values, e.g., `SELECT 0.3333;`.
- A. The old behavior of to_string is to always print to 6 decimal places.
- Failure case: prints 0.333333333 as 0.333333.
- B. The fmt lib will print as many decimal places as are available, but will not be able to print trailing 0s.
- Failure case: prints 0.333000 as 0.333.
- C. If we want to print …

Port TPL behavior for float literals. Change print behavior for REAL.

---

src/execution/compiler/compilation_context.cpp
src/execution/compiler/compiler.cpp
src/execution/compiler/executable_query.cpp
src/execution/compiler/executable_query_builder.cpp
src/execution/vm/module.cpp
src/include/execution/compiler/compilation_context.h
src/include/execution/compiler/compiler.h
src/include/execution/compiler/compiler_settings.h
src/include/execution/compiler/executable_query.h
src/include/execution/compiler/executable_query_builder.h
src/include/execution/exec/execution_settings.h
src/include/execution/vm/module.h
src/include/execution/vm/module_metadata.h
src/include/traffic_cop/traffic_cop.h
src/network/postgres/postgres_network_commands.cpp
src/traffic_cop/traffic_cop.cpp
test/execution/atomics_test.cpp
test/execution/compiler_test.cpp
test/include/execution/vm/module_compiler.h
util/execution/tpl.cpp

First pass at supplying backend for EXPLAIN (FORMAT TPL) queries.
#1588 provides the frontend for EXPLAIN (FORMAT ...) queries.
This PR attempts to provide the backend to that, structured as follows:
- `ExecutionSettings` is currently described as "ExecutionSettings stores settings that are passed down from the upper layers.", so we are passing down a new `CompilerSettings` that determines what information should be gathered at compile-time. This can be set from the tcop upon detecting that this is an EXPLAIN statement of a relevant type. See comment below.
- `CompilerSettings` just describes whether to collect TPL and/or TBC, and is threaded down into `compiler.cpp`.
- Information is maintained in `CompileTimeModuleMetadata` which is currently just a `unordered_map<string, string>`. Two …

Backend for EXPLAIN (FORMAT TPL) queries.

---

src/include/parser/explain_statement.h
src/include/traffic_cop/traffic_cop.h
src/network/postgres/postgres_network_commands.cpp
src/parser/postgresparser.cpp
src/traffic_cop/traffic_cop.cpp

This PR adds support for `explain (format tpl) select * from foo;` and `explain (format tbc) select * from foo;`.
---
This branch has the front-end work (`PostgresParser`, `TrafficCop`, `ExplainStatement`, etc.) for `EXPLAIN (FORMAT TPL) ...` to get TPL of queries back via SQL. However, it still remains unclear how to accomplish the back-end work. `AstPrettyPrint` works on an AST, but that's ephemeral and discarded after compilation. Saving that with the `ExecutableQuery` every time seems wasteful (and maybe incorrect, not sure of the AST's memory life cycle). Instead we could build the string in the compilation phase, but then the question becomes how do we return it back? Is there an empty string in every `CompilationContext` that can optionally retain the TPL AST that's been …

EXPLAIN (FORMAT TPL) and EXPLAIN (FORMAT TBC).

---

src/include/transaction/transaction_context.h
src/storage/record_buffer.cpp
src/traffic_cop/traffic_cop.cpp
src/transaction/transaction_manager.cpp

Fix DurabilityPolicy::DISABLE configuration.
Fix #1595.
- Allow ReplicationPolicy::DISABLE to be set if DurabilityPolicy::DISABLE is also set.
- Immediately release the buffer segment if durability is disabled.
- Immediately remove any txn that commits if durability is disabled. (is this fine?)
Essentially trying to emulate the log manager off configuration.

Fix DurabilityPolicy::DISABLE configuration.

---

src/include/loggers/loggers_util.h
src/include/main/db_main.h
src/include/metrics/metrics_util.h
src/include/settings/settings_callbacks.h
src/include/settings/settings_defs.h
src/include/settings/settings_manager.h
src/include/settings/settings_param.h
src/loggers/loggers_util.cpp
src/settings/settings_callbacks.cpp
src/traffic_cop/traffic_cop.cpp

Add support for arbitrary SHOW. Add "set log_level_blah".
Fix #1188.
Added support for arbitrary SHOW.
This requires exposing GetParam from settings -- ok?
Added set log_level_(binder|catalog|etc) support.
e.g., `set log_level_binder = 'debug'`
Also fix set query_trace_metrics_output which would ASAN out if you actually tried to use it.
If anyone has objections to exposing `settings_manager_->GetParam(std::string)` please bring them up.

Add support for arbitrary SHOW. Add "set log_level_blah".

---

src/include/catalog/catalog.h
src/include/execution/compiler/executable_query.h
src/include/execution/exec/execution_settings.h
src/include/main/db_main.h
src/include/metrics/pipeline_metric.h
src/include/self_driving/forecasting/workload_forecast.h
src/include/self_driving/planning/mcts/monte_carlo_tree_search.h
src/include/self_driving/planning/mcts/tree_node.h
src/include/self_driving/planning/pilot.h
src/include/self_driving/planning/pilot_thread.h
src/include/self_driving/planning/pilot_util.h
src/self_driving/planning/pilot.cpp
src/self_driving/planning/pilot_thread.cpp
src/self_driving/planning/pilot_util.cpp

We have mixed namespace usage for code under the `self_driving/planning` folder. This PR makes them all under the `noisepage::selfdriving::pilot` namespace. I don't really think this needs review.

Unify pilot namespace

---

.gitignore
CMakeLists.txt

Add PYTHONPATH to tests in CMake. Ignore cmake-build-relwithdebinfo.
- Add cmake-build-relwithdebinfo to gitignore.
- Make self-driving tests extra verbose.
- Set PYTHONPATH for tests. See #1612.
Going to see whether it produces a reasonable amount of output in CI for the self-driving tests.

Add PYTHONPATH to tests in CMake. Ignore cmake-build-relwithdebinfo. Verbose self-driving tests.

---

script/testing/oltpbench/constants.py

Clone oltpbench with depth 1.
The OLTPBench repo is pretty big and we clone it at least 4 times in running any forecasting/pilot-related scripts (because the abstractions end up doing something like: repeat 4 times { download oltpbench, run oltpbench, delete oltpbench })
This just makes the clone a little less expensive.
Seeing if this broke CI in any way. I don't think we'd be checking out old branches of oltpbench though.
I'm inclined to argue that this is a point in favor of repetitive but readable bash scripts over python abstractions that are rarely really reusable, but that's a future thing.

Clone oltpbench with depth 1.

---

src/network/connection_handle.cpp

In theory this should just be error messages and not partial query data, but I don't completely understand the network state machine. This is mostly to make sure we flush error messages on connection startup. See `PostgresProtocolInterpreter::ProcessStartup`'s error states.
This came from @lmwnshn seeing behavior where clients couldn't connect while a simultaneous transaction was running that made DDL changes. We now get the verbose error (that was always written to the packet, just never flushed) returned to the client.
Client 1:
```
$ psql -h localhost -p 15721 -d noisepage
psql (12.7 (Ubuntu 12.7-0ubuntu0.20.04.1), server 9.5devel)
Type "help" for help.
noisepage=# begin;
BEGIN
Time: 1.427 ms
noisepage=# create table foo (id int);
CREATE TABLE
Time: 7.825 ms
noisepage=# 
```
Client 2: …

Flush pending writes on connection close

---

src/include/catalog/schema.h

The CTE PR added a new constructor for the `Column` type but neglected to include a call to `Column::Validate()` to validate instances upon construction. This PR adds this missing validation step.

Add Validation to Column Constructor

---

src/include/traffic_cop/traffic_cop.h
src/network/postgres/postgres_network_commands.cpp
src/network/postgres/postgres_packet_util.cpp
src/traffic_cop/traffic_cop.cpp

Refactor support for SHOW commands in DESCRIBE.
Previously, DESCRIBE was writing NO DATA for SHOW.
This fix makes the HikariCP connection pool in the new version of OLTPBench happy.
- Get through CI.

Refactor support for SHOW commands in DESCRIBE.

---

Jenkinsfile-utils.groovy

Excerpt from the Modeling stage in Jenkins:
```
-- Coverage: ON
-- Unity builds (NOISEPAGE_UNITY_BUILD): ON
```
Unity builds break coverage calculations, so we should make sure to turn it off if coverage is on. Maybe we should make the CMake configuration fail if those are both set to ON?

disable unity build for modeling coverage.

---

src/execution/sql/sql.cpp

There are a few inconsistencies in the conversion between `SqlTypeId` and string. I encountered this issue when I was using the query traces for the pilot.
We seem to have the convention that directly uses type names as their string representations (case sensitive). This PR makes those conversions consistent.

Fix the conversion between SqlTypeId and string

---

Jenkinsfile-utils.groovy

This stage does not produce any junit results anyway.  The junit
Jenkins plugin prior to version 1.53 would silently ignore missing &
empty test result files.  As of version 1.53, it produces an error that
fails the stage.
Signed-off-by: Chad Dougherty <crd@acm.org>

remove junit from microbenchmark stage
